export const mockBrokers = [
  {
    id: "maria-alfaro",
    fullName: "Maria Alfaro",
    name: "Maria Alfaro",
    avatarInitials: "MA",
    avatarPlaceholder: "MA",
    location: "Escazu, San Jose",
    province: "San Jose",
    canton: "Escazu",
    district: "San Rafael",
    specialty: "Urban redevelopment and commercial corridors",
    yearsExperience: 12,
    experience: "12 years",
    phone: "+506 2220 1840",
    email: "maria.alfaro@allstateintelligence.com",
    rating: "4.9",
    propertiesManaged: 46,
    bio:
      "Maria supports owners and investors with pricing strategy, municipal readiness, and broker-led listing preparation for high-visibility urban assets.",
    serviceAreas: ["Escazu", "Santa Ana", "Rohrmoser", "San Pedro"],
    languages: ["English", "Spanish"],
    specialties: ["Mixed-use sites", "Commercial lots", "Owner representation"],
    recentPropertyTypes: ["Commercial corner", "Mixed-use parcel", "Urban lot"],
    recentProperties: ["Escazu Mixed-Use Corner", "Sabana Norte Redevelopment Site", "Santa Ana Service Corridor"],
  },
  {
    id: "carlos-rojas",
    fullName: "Carlos Rojas",
    name: "Carlos Rojas",
    avatarInitials: "CR",
    avatarPlaceholder: "CR",
    location: "Tamarindo, Guanacaste",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Tamarindo",
    specialty: "Hospitality land and coastal investment sites",
    yearsExperience: 9,
    experience: "9 years",
    phone: "+506 2653 0911",
    email: "carlos.rojas@allstateintelligence.com",
    rating: "4.8",
    propertiesManaged: 31,
    bio:
      "Carlos focuses on tourism-led properties where access, water availability, and zoning restrictions need careful review before market launch.",
    serviceAreas: ["Tamarindo", "Nosara", "Liberia", "Playa Grande"],
    languages: ["English", "Spanish"],
    specialties: ["Tourism land", "Hospitality concepts", "Coastal due diligence"],
    recentPropertyTypes: ["Hospitality land", "Beachfront opportunity", "Tourism development land"],
    recentProperties: ["Tamarindo Hospitality Lot", "Santa Cruz Boutique Villas Site", "Liberia Airport Corridor Parcel"],
  },
  {
    id: "ana-campos",
    fullName: "Ana Campos",
    name: "Ana Campos",
    avatarInitials: "AC",
    avatarPlaceholder: "AC",
    location: "Heredia, Heredia",
    province: "Heredia",
    canton: "Heredia",
    district: "Mercedes",
    specialty: "Residential redevelopment and student housing",
    yearsExperience: 7,
    experience: "7 years",
    phone: "+506 2260 4418",
    email: "ana.campos@allstateintelligence.com",
    rating: "4.7",
    propertiesManaged: 28,
    bio:
      "Ana helps property owners organize intake records, comparable evidence, and positioning for residential infill and rental-driven projects.",
    serviceAreas: ["Heredia", "Mercedes", "Belen", "Alajuela"],
    languages: ["English", "Spanish"],
    specialties: ["Residential redevelopment", "Student housing", "Rental analysis"],
    recentPropertyTypes: ["Residential development land", "Urban lot", "Infill parcel"],
    recentProperties: ["Heredia Student Housing Site", "Mercedes Multifamily Parcel", "Belen Infill Opportunity"],
  },
  {
    id: "diego-vargas",
    fullName: "Diego Vargas",
    name: "Diego Vargas",
    avatarInitials: "DV",
    avatarPlaceholder: "DV",
    location: "Lindora, Santa Ana",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Pozos",
    specialty: "Logistics parcels and west corridor industrial land",
    yearsExperience: 11,
    experience: "11 years",
    phone: "+506 2204 7712",
    email: "diego.vargas@allstateintelligence.com",
    rating: "4.9",
    propertiesManaged: 39,
    bio:
      "Diego works with owners of logistics and flex-industrial land near Ruta 27, Forum, Lindora, and airport-connected corridors.",
    serviceAreas: ["Lindora", "Santa Ana", "Belen", "Alajuela"],
    languages: ["English", "Spanish"],
    specialties: ["Industrial lots", "Logistics parcels", "Last-mile distribution"],
    recentPropertyTypes: ["Industrial lot", "Logistics parcel", "Commercial service lot"],
    recentProperties: ["Santa Ana Logistics Parcel", "Belen Warehouse Edge", "Coyol Light Industrial Lot"],
  },
  {
    id: "laura-mendez",
    fullName: "Laura Mendez",
    name: "Laura Mendez",
    avatarInitials: "LM",
    avatarPlaceholder: "LM",
    location: "Curridabat, San Jose",
    province: "San Jose",
    canton: "Curridabat",
    district: "Granadilla",
    specialty: "East-side mixed-use and institutional corridor sites",
    yearsExperience: 8,
    experience: "8 years",
    phone: "+506 2272 6504",
    email: "laura.mendez@allstateintelligence.com",
    rating: "4.8",
    propertiesManaged: 34,
    bio:
      "Laura coordinates pricing, zoning review, and investor packaging for east San Jose assets near universities, offices, and medical services.",
    serviceAreas: ["Curridabat", "San Pedro", "Zapote", "Tres Rios"],
    languages: ["English", "Spanish"],
    specialties: ["Mixed-use parcels", "Urban lots", "Institutional corridors"],
    recentPropertyTypes: ["Mixed-use parcel", "Commercial corner", "Residential development land"],
    recentProperties: ["Curridabat Mixed-Use Parcel", "San Pedro Corner Site", "Granadilla Medical Corridor Lot"],
  },
  {
    id: "andres-solis",
    fullName: "Andres Solis",
    name: "Andres Solis",
    avatarInitials: "AS",
    avatarPlaceholder: "AS",
    location: "Liberia, Guanacaste",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Liberia",
    specialty: "Airport corridor land and regional commercial sites",
    yearsExperience: 10,
    experience: "10 years",
    phone: "+506 2666 3810",
    email: "andres.solis@allstateintelligence.com",
    rating: "4.7",
    propertiesManaged: 37,
    bio:
      "Andres advises owners near Liberia airport, Ruta 21, and regional service nodes on value range, absorption, and infrastructure readiness.",
    serviceAreas: ["Liberia", "Papagayo", "Canas Dulces", "Bagaces"],
    languages: ["English", "Spanish"],
    specialties: ["Airport corridor land", "Commercial lots", "Regional services"],
    recentPropertyTypes: ["Commercial corner", "Logistics parcel", "Tourism development land"],
    recentProperties: ["Liberia Airport Service Lot", "Ruta 21 Commercial Frontage", "Papagayo Support Parcel"],
  },
  {
    id: "sofia-quesada",
    fullName: "Sofia Quesada",
    name: "Sofia Quesada",
    avatarInitials: "SQ",
    avatarPlaceholder: "SQ",
    location: "Jaco, Puntarenas",
    province: "Puntarenas",
    canton: "Garabito",
    district: "Jaco",
    specialty: "Beach town commercial and hospitality opportunities",
    yearsExperience: 6,
    experience: "6 years",
    phone: "+506 2643 9914",
    email: "sofia.quesada@allstateintelligence.com",
    rating: "4.6",
    propertiesManaged: 24,
    bio:
      "Sofia supports coastal owners with listing readiness, tourism demand context, and review of access, utilities, and seasonal liquidity.",
    serviceAreas: ["Jaco", "Herradura", "Tarcoles", "Playa Hermosa"],
    languages: ["English", "Spanish"],
    specialties: ["Hospitality land", "Beachfront opportunities", "Tourism commercial"],
    recentPropertyTypes: ["Beachfront opportunity", "Hospitality land", "Commercial corner"],
    recentProperties: ["Jaco Beachfront Opportunity", "Herradura Boutique Hotel Land", "Hermosa Surf Corridor Parcel"],
  },
  {
    id: "esteban-mora",
    fullName: "Esteban Mora",
    name: "Esteban Mora",
    avatarInitials: "EM",
    avatarPlaceholder: "EM",
    location: "Grecia, Alajuela",
    province: "Alajuela",
    canton: "Grecia",
    district: "Grecia",
    specialty: "Mountain view residential land and family development sites",
    yearsExperience: 9,
    experience: "9 years",
    phone: "+506 2494 1187",
    email: "esteban.mora@allstateintelligence.com",
    rating: "4.7",
    propertiesManaged: 30,
    bio:
      "Esteban works with owners in the western valley, emphasizing access, slope, utility delivery, and realistic family residential demand.",
    serviceAreas: ["Grecia", "Atenas", "Sarchi", "Naranjo"],
    languages: ["English", "Spanish"],
    specialties: ["Residential development land", "Mountain eco-lots", "Small farms"],
    recentPropertyTypes: ["Mountain eco-lot", "Residential development land", "Urban lot"],
    recentProperties: ["Grecia View Residential Land", "Atenas Ridge Lot", "Sarchi Family Compound Site"],
  },
  {
    id: "valeria-castro",
    fullName: "Valeria Castro",
    name: "Valeria Castro",
    avatarInitials: "VC",
    avatarPlaceholder: "VC",
    location: "Cartago, Cartago",
    province: "Cartago",
    canton: "Cartago",
    district: "Oriental",
    specialty: "Industrial support land and residential expansion parcels",
    yearsExperience: 13,
    experience: "13 years",
    phone: "+506 2552 7021",
    email: "valeria.castro@allstateintelligence.com",
    rating: "4.8",
    propertiesManaged: 44,
    bio:
      "Valeria guides owners through Cartago zoning, industrial adjacency, and residential growth opportunities along key eastern routes.",
    serviceAreas: ["Cartago", "El Guarco", "Tres Rios", "Paraiso"],
    languages: ["English", "Spanish"],
    specialties: ["Industrial lots", "Residential development land", "Urban expansion"],
    recentPropertyTypes: ["Industrial lot", "Residential development land", "Mixed-use parcel"],
    recentProperties: ["Cartago Industrial Lot", "El Guarco Expansion Land", "Tres Rios Corner Parcel"],
  },
  {
    id: "marco-hidalgo",
    fullName: "Marco Hidalgo",
    name: "Marco Hidalgo",
    avatarInitials: "MH",
    avatarPlaceholder: "MH",
    location: "Nosara, Guanacaste",
    province: "Guanacaste",
    canton: "Nicoya",
    district: "Nosara",
    specialty: "Eco-hospitality and wellness development land",
    yearsExperience: 8,
    experience: "8 years",
    phone: "+506 2682 4140",
    email: "marco.hidalgo@allstateintelligence.com",
    rating: "4.6",
    propertiesManaged: 22,
    bio:
      "Marco works with sellers of low-density coastal and eco-hospitality sites where water, road access, and conservation constraints matter.",
    serviceAreas: ["Nosara", "Samara", "Nicoya", "Ostional"],
    languages: ["English", "Spanish"],
    specialties: ["Mountain eco-lots", "Hospitality land", "Wellness retreats"],
    recentPropertyTypes: ["Mountain eco-lot", "Hospitality land", "Tourism development land"],
    recentProperties: ["Nosara Eco-Lodge Parcel", "Samara Ridge Retreat Land", "Ostional Conservation Edge Lot"],
  },
  {
    id: "paola-jimenez",
    fullName: "Paola Jimenez",
    name: "Paola Jimenez",
    avatarInitials: "PJ",
    avatarPlaceholder: "PJ",
    location: "La Fortuna, Alajuela",
    province: "Alajuela",
    canton: "San Carlos",
    district: "La Fortuna",
    specialty: "Nature tourism land and lodge development opportunities",
    yearsExperience: 10,
    experience: "10 years",
    phone: "+506 2479 3206",
    email: "paola.jimenez@allstateintelligence.com",
    rating: "4.8",
    propertiesManaged: 33,
    bio:
      "Paola specializes in volcano-view and hot-springs corridor properties, pairing owner expectations with access and tourism demand evidence.",
    serviceAreas: ["La Fortuna", "El Tanque", "Muelle", "Arenal"],
    languages: ["English", "Spanish"],
    specialties: ["Hospitality land", "Mountain eco-lots", "Tourism development"],
    recentPropertyTypes: ["Hospitality land", "Mountain eco-lot", "Tourism development land"],
    recentProperties: ["La Fortuna Lodge Site", "Arenal View Eco-Lot", "El Tanque Tourism Parcel"],
  },
  {
    id: "gabriel-arias",
    fullName: "Gabriel Arias",
    name: "Gabriel Arias",
    avatarInitials: "GA",
    avatarPlaceholder: "GA",
    location: "Rohrmoser, San Jose",
    province: "San Jose",
    canton: "San Jose",
    district: "Pavas",
    specialty: "High-density infill and embassy corridor properties",
    yearsExperience: 14,
    experience: "14 years",
    phone: "+506 2291 4077",
    email: "gabriel.arias@allstateintelligence.com",
    rating: "4.9",
    propertiesManaged: 52,
    bio:
      "Gabriel helps owners in mature urban neighborhoods align pricing with redevelopment potential, density, parking, and buyer liquidity.",
    serviceAreas: ["Rohrmoser", "Pavas", "La Sabana", "Mata Redonda"],
    languages: ["English", "Spanish"],
    specialties: ["Urban lots", "Residential redevelopment", "Commercial corners"],
    recentPropertyTypes: ["Urban lot", "Commercial corner", "Residential development land"],
    recentProperties: ["Rohrmoser Embassy Corridor Lot", "Pavas Mixed-Use Parcel", "Sabana Norte Redevelopment Site"],
  },
  {
    id: "natalia-leiva",
    fullName: "Natalia Leiva",
    name: "Natalia Leiva",
    avatarInitials: "NL",
    avatarPlaceholder: "NL",
    location: "San Pedro, San Jose",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "San Pedro",
    specialty: "University corridor and student housing properties",
    yearsExperience: 6,
    experience: "6 years",
    phone: "+506 2253 8802",
    email: "natalia.leiva@allstateintelligence.com",
    rating: "4.6",
    propertiesManaged: 26,
    bio:
      "Natalia supports compact owner sites with student housing, services, and transit-oriented positioning near east-side universities.",
    serviceAreas: ["San Pedro", "Sabanilla", "Curridabat", "Los Yoses"],
    languages: ["English", "Spanish", "Portuguese"],
    specialties: ["Student housing", "Urban lots", "Mixed-use parcels"],
    recentPropertyTypes: ["Residential development land", "Mixed-use parcel", "Urban lot"],
    recentProperties: ["San Pedro Student Housing Lot", "Los Yoses Redevelopment Site", "Sabanilla Infill Parcel"],
  },
  {
    id: "oscar-benavides",
    fullName: "Oscar Benavides",
    name: "Oscar Benavides",
    avatarInitials: "OB",
    avatarPlaceholder: "OB",
    location: "Alajuela, Alajuela",
    province: "Alajuela",
    canton: "Alajuela",
    district: "Alajuela",
    specialty: "Airport logistics and industrial expansion parcels",
    yearsExperience: 15,
    experience: "15 years",
    phone: "+506 2430 5722",
    email: "oscar.benavides@allstateintelligence.com",
    rating: "4.9",
    propertiesManaged: 58,
    bio:
      "Oscar advises industrial owners around SJO airport, Coyol, and Route 1 on land value, utilities, access, and institutional buyer needs.",
    serviceAreas: ["Alajuela", "Coyol", "Rio Segundo", "Belen"],
    languages: ["English", "Spanish"],
    specialties: ["Industrial lots", "Logistics parcels", "Airport corridor land"],
    recentPropertyTypes: ["Logistics parcel", "Industrial lot", "Commercial service lot"],
    recentProperties: ["Alajuela Airport Logistics Parcel", "Coyol Expansion Site", "Rio Segundo Warehouse Land"],
  },
  {
    id: "isabel-nunez",
    fullName: "Isabel Nunez",
    name: "Isabel Nunez",
    avatarInitials: "IN",
    avatarPlaceholder: "IN",
    location: "Belen, Heredia",
    province: "Heredia",
    canton: "Belen",
    district: "La Ribera",
    specialty: "Corporate corridor and business park support properties",
    yearsExperience: 8,
    experience: "8 years",
    phone: "+506 2239 6618",
    email: "isabel.nunez@allstateintelligence.com",
    rating: "4.7",
    propertiesManaged: 29,
    bio:
      "Isabel works on service, office, and light industrial properties near business parks, hotels, and airport-linked demand.",
    serviceAreas: ["Belen", "La Ribera", "Cariari", "Ulloa"],
    languages: ["English", "Spanish"],
    specialties: ["Commercial lots", "Logistics parcels", "Mixed-use parcels"],
    recentPropertyTypes: ["Commercial corner", "Logistics parcel", "Mixed-use parcel"],
    recentProperties: ["Belen Corporate Corridor Lot", "Cariari Service Parcel", "La Ribera Flex-Site"],
  },
  {
    id: "renato-fonseca",
    fullName: "Renato Fonseca",
    name: "Renato Fonseca",
    avatarInitials: "RF",
    avatarPlaceholder: "RF",
    location: "Santa Ana, San Jose",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Lindora",
    specialty: "Premium west-side development and commercial frontage",
    yearsExperience: 16,
    experience: "16 years",
    phone: "+506 2203 4970",
    email: "renato.fonseca@allstateintelligence.com",
    rating: "5.0",
    propertiesManaged: 63,
    bio:
      "Renato manages strategic west-side listings that require careful pricing, access confirmation, and investor-grade marketing packages.",
    serviceAreas: ["Lindora", "Pozos", "Santa Ana", "Escazu"],
    languages: ["English", "Spanish"],
    specialties: ["Commercial frontage", "Mixed-use parcels", "Premium infill"],
    recentPropertyTypes: ["Commercial corner", "Mixed-use parcel", "Urban lot"],
    recentProperties: ["Lindora Commercial Frontage", "Pozos Service Lot", "Santa Ana Office-Retail Site"],
  },
  {
    id: "karla-picado",
    fullName: "Karla Picado",
    name: "Karla Picado",
    avatarInitials: "KP",
    avatarPlaceholder: "KP",
    location: "Cartago, Cartago",
    province: "Cartago",
    canton: "La Union",
    district: "Tres Rios",
    specialty: "Eastern residential growth and mixed-use parcels",
    yearsExperience: 7,
    experience: "7 years",
    phone: "+506 2279 3341",
    email: "karla.picado@allstateintelligence.com",
    rating: "4.6",
    propertiesManaged: 21,
    bio:
      "Karla supports owners near eastern growth corridors with residential, mixed-use, and services-led positioning.",
    serviceAreas: ["Tres Rios", "Concepcion", "Curridabat", "Cartago"],
    languages: ["English", "Spanish"],
    specialties: ["Residential development land", "Mixed-use parcels", "Commercial lots"],
    recentPropertyTypes: ["Residential development land", "Mixed-use parcel", "Urban lot"],
    recentProperties: ["Tres Rios Residential Land", "Concepcion Mixed-Use Corner", "La Union Family Housing Site"],
  },
  {
    id: "manuel-cordero",
    fullName: "Manuel Cordero",
    name: "Manuel Cordero",
    avatarInitials: "MC",
    avatarPlaceholder: "MC",
    location: "Atenas, Alajuela",
    province: "Alajuela",
    canton: "Atenas",
    district: "Atenas",
    specialty: "Mountain lifestyle land and expat residential parcels",
    yearsExperience: 12,
    experience: "12 years",
    phone: "+506 2446 0912",
    email: "manuel.cordero@allstateintelligence.com",
    rating: "4.8",
    propertiesManaged: 36,
    bio:
      "Manuel handles hillside and view parcels where road grade, buildability, water source, and owner price expectations need early validation.",
    serviceAreas: ["Atenas", "Grecia", "Orotina", "Naranjo"],
    languages: ["English", "Spanish"],
    specialties: ["Mountain eco-lots", "Residential development land", "Small farms"],
    recentPropertyTypes: ["Mountain eco-lot", "Residential development land", "Lifestyle farm"],
    recentProperties: ["Atenas Valley View Lot", "Orotina Ridge Parcel", "Naranjo Residential Land"],
  },
  {
    id: "monica-salas",
    fullName: "Monica Salas",
    name: "Monica Salas",
    avatarInitials: "MS",
    avatarPlaceholder: "MS",
    location: "Escazu, San Jose",
    province: "San Jose",
    canton: "Escazu",
    district: "Guachipelin",
    specialty: "Corporate office-adjacent lots and premium residential land",
    yearsExperience: 10,
    experience: "10 years",
    phone: "+506 2288 7095",
    email: "monica.salas@allstateintelligence.com",
    rating: "4.8",
    propertiesManaged: 35,
    bio:
      "Monica prepares owner assets near premium schools, hospitals, and office clusters for investor review and broker listing.",
    serviceAreas: ["Guachipelin", "San Rafael", "Escazu", "Santa Ana"],
    languages: ["English", "Spanish", "French"],
    specialties: ["Commercial lots", "Premium residential land", "Mixed-use sites"],
    recentPropertyTypes: ["Commercial corner", "Urban lot", "Mixed-use parcel"],
    recentProperties: ["Guachipelin Office Edge Lot", "Escazu School Corridor Parcel", "San Rafael Premium Lot"],
  },
  {
    id: "ricardo-sanchez",
    fullName: "Ricardo Sanchez",
    name: "Ricardo Sanchez",
    avatarInitials: "RS",
    avatarPlaceholder: "RS",
    location: "San Ramon, Alajuela",
    province: "Alajuela",
    canton: "San Ramon",
    district: "San Ramon",
    specialty: "Regional residential land and highway-access parcels",
    yearsExperience: 8,
    experience: "8 years",
    phone: "+506 2445 6184",
    email: "ricardo.sanchez@allstateintelligence.com",
    rating: "4.5",
    propertiesManaged: 25,
    bio:
      "Ricardo works with owners outside the GAM core, balancing affordability, road access, and realistic absorption for regional buyers.",
    serviceAreas: ["San Ramon", "Palmares", "Naranjo", "Grecia"],
    languages: ["Spanish", "English"],
    specialties: ["Residential development land", "Urban lots", "Mountain eco-lots"],
    recentPropertyTypes: ["Residential development land", "Urban lot", "Mountain eco-lot"],
    recentProperties: ["San Ramon Residential Parcel", "Palmares Urban Lot", "Naranjo View Land"],
  },
];

export const selectedBrokerStorageKey = "asi:selectedBrokerId";

export function findBrokerById(id) {
  return mockBrokers.find((broker) => broker.id === id) || null;
}
