function makeComparable(comparable) {
  const askingPrice = Math.round(comparable.landSizeM2 * comparable.pricePerM2);

  return {
    ...comparable,
    name: comparable.title,
    landSize: comparable.landSizeM2,
    askingPrice,
    ownerPrice: askingPrice,
    latitude: comparable.coordinates.lat,
    longitude: comparable.coordinates.lng,
    distanceFromSelected: null,
  };
}

export const comparableProperties = [
  makeComparable({
    id: "comp-escazu-san-rafael-commercial-corner",
    title: "San Rafael Commercial Corner",
    province: "San Jose",
    canton: "Escazu",
    district: "San Rafael",
    coordinates: { lat: 9.9369, lng: -84.1412 },
    propertyType: "commercial corner",
    landSizeM2: 1180,
    pricePerM2: 1185,
    landUse: "Mixed-use commercial corridor",
    similarityScore: 94,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "High frontage corner near retail anchors and private medical demand.",
  }),
  makeComparable({
    id: "comp-escazu-guachipelin-office-edge",
    title: "Guachipelin Office Edge Lot",
    province: "San Jose",
    canton: "Escazu",
    district: "Guachipelin",
    coordinates: { lat: 9.9485, lng: -84.1541 },
    propertyType: "urban lot",
    landSizeM2: 2100,
    pricePerM2: 930,
    landUse: "Office and services",
    similarityScore: 88,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Comparable west-side office support parcel with premium access.",
  }),
  makeComparable({
    id: "comp-escazu-trejos-montealegre-infill",
    title: "Trejos Montealegre Infill Parcel",
    province: "San Jose",
    canton: "Escazu",
    district: "San Rafael",
    coordinates: { lat: 9.9351, lng: -84.1374 },
    propertyType: "mixed-use parcel",
    landSizeM2: 1425,
    pricePerM2: 1260,
    landUse: "Commercial-residential mixed use",
    similarityScore: 92,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Closed transaction with strong commercial frontage evidence.",
  }),
  makeComparable({
    id: "comp-escazu-bello-horizonte-residential",
    title: "Bello Horizonte Residential Development Land",
    province: "San Jose",
    canton: "Escazu",
    district: "Escazu",
    coordinates: { lat: 9.9208, lng: -84.1379 },
    propertyType: "residential development land",
    landSizeM2: 2650,
    pricePerM2: 705,
    landUse: "Medium-density residential",
    similarityScore: 76,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Residential use limits direct comparability but supports Escazu land floor.",
  }),
  makeComparable({
    id: "comp-santa-ana-pozos-logistics",
    title: "Pozos Logistics Support Lot",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Pozos",
    coordinates: { lat: 9.9341, lng: -84.1811 },
    propertyType: "logistics parcel",
    landSizeM2: 4600,
    pricePerM2: 515,
    landUse: "Light industrial and services",
    similarityScore: 96,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Similar lot size and Route 27 access profile.",
  }),
  makeComparable({
    id: "comp-santa-ana-lindora-frontage",
    title: "Lindora Commercial Frontage",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Lindora",
    coordinates: { lat: 9.9503, lng: -84.1882 },
    propertyType: "commercial corner",
    landSizeM2: 1720,
    pricePerM2: 845,
    landUse: "Retail and services",
    similarityScore: 84,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Stronger retail exposure but smaller industrial utility profile.",
  }),
  makeComparable({
    id: "comp-santa-ana-brasil-industrial",
    title: "Brasil Light Industrial Yard",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Brasil",
    coordinates: { lat: 9.9442, lng: -84.2026 },
    propertyType: "industrial lot",
    landSizeM2: 5200,
    pricePerM2: 405,
    landUse: "Industrial services",
    similarityScore: 82,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Useful lower-bound evidence for truck-oriented land.",
  }),
  makeComparable({
    id: "comp-santa-ana-piedades-residential",
    title: "Piedades Residential Expansion Site",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Piedades",
    coordinates: { lat: 9.9294, lng: -84.2192 },
    propertyType: "residential development land",
    landSizeM2: 3800,
    pricePerM2: 365,
    landUse: "Residential expansion",
    similarityScore: 62,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Included as geographic but not use-type equivalent evidence.",
  }),
  makeComparable({
    id: "comp-heredia-mercedes-student",
    title: "Mercedes Student Housing Parcel",
    province: "Heredia",
    canton: "Heredia",
    district: "Mercedes",
    coordinates: { lat: 10.0031, lng: -84.1152 },
    propertyType: "residential development land",
    landSizeM2: 1020,
    pricePerM2: 615,
    landUse: "Medium-density residential",
    similarityScore: 95,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Comparable walkable student housing candidate near UNA.",
  }),
  makeComparable({
    id: "comp-heredia-ulloa-corporate",
    title: "Ulloa Corporate Support Parcel",
    province: "Heredia",
    canton: "Heredia",
    district: "Ulloa",
    coordinates: { lat: 9.9792, lng: -84.1354 },
    propertyType: "mixed-use parcel",
    landSizeM2: 1850,
    pricePerM2: 545,
    landUse: "Office-service mixed use",
    similarityScore: 74,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Corporate demand comparable, less residential than Mercedes.",
  }),
  makeComparable({
    id: "comp-heredia-belen-infill",
    title: "Belen Infill Opportunity",
    province: "Heredia",
    canton: "Belen",
    district: "La Ribera",
    coordinates: { lat: 9.9824, lng: -84.1748 },
    propertyType: "urban lot",
    landSizeM2: 1380,
    pricePerM2: 585,
    landUse: "Urban residential-commercial",
    similarityScore: 71,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Useful GAM west Heredia infill reference.",
  }),
  makeComparable({
    id: "comp-heredia-san-francisco-residential",
    title: "San Francisco Residential Corner",
    province: "Heredia",
    canton: "Heredia",
    district: "San Francisco",
    coordinates: { lat: 9.9933, lng: -84.1178 },
    propertyType: "residential development land",
    landSizeM2: 760,
    pricePerM2: 660,
    landUse: "Residential redevelopment",
    similarityScore: 87,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Smaller lot with close urban residential demand.",
  }),
  makeComparable({
    id: "comp-tamarindo-beach-corridor",
    title: "Tamarindo Beach Corridor Land",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Tamarindo",
    coordinates: { lat: 10.3001, lng: -85.8358 },
    propertyType: "hospitality land",
    landSizeM2: 2550,
    pricePerM2: 610,
    landUse: "Tourism commercial",
    similarityScore: 96,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Direct tourism corridor comparable with similar boutique lodging potential.",
  }),
  makeComparable({
    id: "comp-tamarindo-langosta-villas",
    title: "Langosta Villas Development Lot",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Tamarindo",
    coordinates: { lat: 10.2922, lng: -85.8458 },
    propertyType: "hospitality land",
    landSizeM2: 1880,
    pricePerM2: 705,
    landUse: "Tourism residential",
    similarityScore: 88,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Premium beach proximity but smaller development envelope.",
  }),
  makeComparable({
    id: "comp-tamarindo-villareal-service",
    title: "Villareal Service Lot",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Tamarindo",
    coordinates: { lat: 10.3191, lng: -85.8077 },
    propertyType: "commercial corner",
    landSizeM2: 3100,
    pricePerM2: 325,
    landUse: "Service commercial",
    similarityScore: 69,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Lower price inland support reference.",
  }),
  makeComparable({
    id: "comp-tamarindo-playa-grande-edge",
    title: "Playa Grande Hospitality Edge",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Cabo Velas",
    coordinates: { lat: 10.3334, lng: -85.8421 },
    propertyType: "tourism development land",
    landSizeM2: 4200,
    pricePerM2: 465,
    landUse: "Tourism and villas",
    similarityScore: 73,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Larger tourism land reference outside the main Tamarindo core.",
  }),
  makeComparable({
    id: "comp-liberia-airport-service",
    title: "Liberia Airport Service Lot",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Liberia",
    coordinates: { lat: 10.5925, lng: -85.5482 },
    propertyType: "commercial corner",
    landSizeM2: 3600,
    pricePerM2: 295,
    landUse: "Airport services",
    similarityScore: 87,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Airport-proximate service parcel with regional traffic.",
  }),
  makeComparable({
    id: "comp-liberia-ruta21-logistics",
    title: "Ruta 21 Logistics Parcel",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Liberia",
    coordinates: { lat: 10.6157, lng: -85.4524 },
    propertyType: "logistics parcel",
    landSizeM2: 7800,
    pricePerM2: 175,
    landUse: "Logistics and storage",
    similarityScore: 76,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Large regional logistics reference with lower per-meter pricing.",
  }),
  makeComparable({
    id: "comp-liberia-papagayo-support",
    title: "Papagayo Support Parcel",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Nacascolo",
    coordinates: { lat: 10.6284, lng: -85.6472 },
    propertyType: "tourism development land",
    landSizeM2: 5200,
    pricePerM2: 260,
    landUse: "Tourism support services",
    similarityScore: 70,
    saleStatus: "Listed",
    sourceType: "Internal estimate",
    notes: "Tourism corridor support land near resort demand.",
  }),
  makeComparable({
    id: "comp-liberia-centro-commercial",
    title: "Liberia Centro Commercial Lot",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Liberia",
    coordinates: { lat: 10.6311, lng: -85.4389 },
    propertyType: "urban lot",
    landSizeM2: 980,
    pricePerM2: 360,
    landUse: "Urban commercial",
    similarityScore: 73,
    saleStatus: "Sold",
    sourceType: "Broker record",
    notes: "Small urban commercial sale with strong central frontage.",
  }),
  makeComparable({
    id: "comp-jaco-beachfront-opportunity",
    title: "Jaco Beachfront Opportunity",
    province: "Puntarenas",
    canton: "Garabito",
    district: "Jaco",
    coordinates: { lat: 9.6141, lng: -84.6297 },
    propertyType: "beachfront opportunity",
    landSizeM2: 1800,
    pricePerM2: 910,
    landUse: "Tourism commercial",
    similarityScore: 90,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Direct beachfront land with high hospitality optionality.",
  }),
  makeComparable({
    id: "comp-jaco-herradura-hospitality",
    title: "Herradura Hospitality Land",
    province: "Puntarenas",
    canton: "Garabito",
    district: "Herradura",
    coordinates: { lat: 9.6501, lng: -84.6574 },
    propertyType: "hospitality land",
    landSizeM2: 3400,
    pricePerM2: 455,
    landUse: "Tourism lodging",
    similarityScore: 78,
    saleStatus: "Pending",
    sourceType: "Broker record",
    notes: "Close marina demand with larger parcel and lower price per meter.",
  }),
  makeComparable({
    id: "comp-jaco-commercial-strip",
    title: "Jaco Commercial Strip Corner",
    province: "Puntarenas",
    canton: "Garabito",
    district: "Jaco",
    coordinates: { lat: 9.6185, lng: -84.6278 },
    propertyType: "commercial corner",
    landSizeM2: 920,
    pricePerM2: 820,
    landUse: "Tourism retail",
    similarityScore: 82,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "High visibility small-lot commercial transaction.",
  }),
  makeComparable({
    id: "comp-jaco-hermosa-surf",
    title: "Hermosa Surf Corridor Parcel",
    province: "Puntarenas",
    canton: "Garabito",
    district: "Jaco",
    coordinates: { lat: 9.5757, lng: -84.6019 },
    propertyType: "hospitality land",
    landSizeM2: 5100,
    pricePerM2: 315,
    landUse: "Tourism residential",
    similarityScore: 69,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Surf tourism reference outside the walkable Jaco center.",
  }),
  makeComparable({
    id: "comp-curridabat-granadilla-medical",
    title: "Granadilla Medical Corridor Lot",
    province: "San Jose",
    canton: "Curridabat",
    district: "Granadilla",
    coordinates: { lat: 9.9181, lng: -84.0195 },
    propertyType: "mixed-use parcel",
    landSizeM2: 1560,
    pricePerM2: 720,
    landUse: "Medical and services",
    similarityScore: 86,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Strong east-side services demand and municipal support.",
  }),
  makeComparable({
    id: "comp-curridabat-pinares-frontage",
    title: "Pinares Retail Frontage",
    province: "San Jose",
    canton: "Curridabat",
    district: "Sanchez",
    coordinates: { lat: 9.9187, lng: -84.0058 },
    propertyType: "commercial corner",
    landSizeM2: 1040,
    pricePerM2: 940,
    landUse: "Retail frontage",
    similarityScore: 80,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Premium retail exposure; smaller site size.",
  }),
  makeComparable({
    id: "comp-curridabat-lomas-mixed",
    title: "Lomas Mixed-Use Parcel",
    province: "San Jose",
    canton: "Curridabat",
    district: "Curridabat",
    coordinates: { lat: 9.9122, lng: -84.0365 },
    propertyType: "mixed-use parcel",
    landSizeM2: 1980,
    pricePerM2: 610,
    landUse: "Residential-commercial mixed use",
    similarityScore: 84,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Balanced evidence for east-side mixed-use parcels.",
  }),
  makeComparable({
    id: "comp-curridabat-sabanilla-student",
    title: "Sabanilla Student Housing Lot",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "Sabanilla",
    coordinates: { lat: 9.9394, lng: -84.0372 },
    propertyType: "residential development land",
    landSizeM2: 890,
    pricePerM2: 555,
    landUse: "Student housing",
    similarityScore: 72,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "University demand reference with residential orientation.",
  }),
  makeComparable({
    id: "comp-grecia-view-residential",
    title: "Grecia View Residential Land",
    province: "Alajuela",
    canton: "Grecia",
    district: "Grecia",
    coordinates: { lat: 10.0735, lng: -84.3117 },
    propertyType: "residential development land",
    landSizeM2: 5200,
    pricePerM2: 165,
    landUse: "Low-density residential",
    similarityScore: 88,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Good family development reference with road and utility access.",
  }),
  makeComparable({
    id: "comp-grecia-sarchi-eco",
    title: "Sarchi Mountain Eco-Lot",
    province: "Alajuela",
    canton: "Sarchi",
    district: "Sarchi Norte",
    coordinates: { lat: 10.0875, lng: -84.3428 },
    propertyType: "mountain eco-lot",
    landSizeM2: 7800,
    pricePerM2: 95,
    landUse: "Eco-residential",
    similarityScore: 70,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Slope and lifestyle demand lower per-meter price.",
  }),
  makeComparable({
    id: "comp-grecia-centro-urban",
    title: "Grecia Centro Urban Lot",
    province: "Alajuela",
    canton: "Grecia",
    district: "Grecia",
    coordinates: { lat: 10.0731, lng: -84.3121 },
    propertyType: "urban lot",
    landSizeM2: 860,
    pricePerM2: 255,
    landUse: "Urban residential",
    similarityScore: 73,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Central lot benchmark for smaller infill assets.",
  }),
  makeComparable({
    id: "comp-grecia-atenas-ridge",
    title: "Atenas Ridge Residential Parcel",
    province: "Alajuela",
    canton: "Atenas",
    district: "Atenas",
    coordinates: { lat: 9.9798, lng: -84.3791 },
    propertyType: "mountain eco-lot",
    landSizeM2: 6400,
    pricePerM2: 145,
    landUse: "Residential lifestyle",
    similarityScore: 66,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Comparable western valley lifestyle lot.",
  }),
  makeComparable({
    id: "comp-alajuela-airport-logistics",
    title: "Alajuela Airport Logistics Parcel",
    province: "Alajuela",
    canton: "Alajuela",
    district: "Rio Segundo",
    coordinates: { lat: 9.9993, lng: -84.2099 },
    propertyType: "logistics parcel",
    landSizeM2: 6400,
    pricePerM2: 445,
    landUse: "Airport logistics",
    similarityScore: 91,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Airport-adjacent comparable with industrial buyer demand.",
  }),
  makeComparable({
    id: "comp-alajuela-coyol-industrial",
    title: "Coyol Light Industrial Lot",
    province: "Alajuela",
    canton: "Alajuela",
    district: "Coyol",
    coordinates: { lat: 9.9928, lng: -84.2503 },
    propertyType: "industrial lot",
    landSizeM2: 9200,
    pricePerM2: 305,
    landUse: "Industrial park support",
    similarityScore: 84,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Larger industrial reference near medical device cluster.",
  }),
  makeComparable({
    id: "comp-alajuela-centro-commercial",
    title: "Alajuela Centro Commercial Lot",
    province: "Alajuela",
    canton: "Alajuela",
    district: "Alajuela",
    coordinates: { lat: 10.0162, lng: -84.2147 },
    propertyType: "commercial corner",
    landSizeM2: 1220,
    pricePerM2: 520,
    landUse: "Commercial services",
    similarityScore: 72,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Central commercial comp with stronger foot traffic.",
  }),
  makeComparable({
    id: "comp-alajuela-la-guacima-residential",
    title: "La Guacima Residential Development Land",
    province: "Alajuela",
    canton: "Alajuela",
    district: "La Guacima",
    coordinates: { lat: 9.9647, lng: -84.2591 },
    propertyType: "residential development land",
    landSizeM2: 4800,
    pricePerM2: 245,
    landUse: "Residential development",
    similarityScore: 65,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Residential demand reference west of the airport.",
  }),
  makeComparable({
    id: "comp-cartago-industrial-lot",
    title: "Cartago Industrial Lot",
    province: "Cartago",
    canton: "Cartago",
    district: "Oriental",
    coordinates: { lat: 9.8669, lng: -83.9197 },
    propertyType: "industrial lot",
    landSizeM2: 5300,
    pricePerM2: 265,
    landUse: "Industrial support",
    similarityScore: 86,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Eastern industrial land reference with services nearby.",
  }),
  makeComparable({
    id: "comp-cartago-tres-rios-corner",
    title: "Tres Rios Mixed-Use Corner",
    province: "Cartago",
    canton: "La Union",
    district: "Tres Rios",
    coordinates: { lat: 9.9068, lng: -83.9876 },
    propertyType: "mixed-use parcel",
    landSizeM2: 1640,
    pricePerM2: 430,
    landUse: "Residential-commercial mixed use",
    similarityScore: 80,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Gateway east-side mixed-use comparable.",
  }),
  makeComparable({
    id: "comp-cartago-el-guarco-residential",
    title: "El Guarco Expansion Land",
    province: "Cartago",
    canton: "El Guarco",
    district: "Tejar",
    coordinates: { lat: 9.8444, lng: -83.9383 },
    propertyType: "residential development land",
    landSizeM2: 6100,
    pricePerM2: 185,
    landUse: "Residential expansion",
    similarityScore: 71,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Suburban residential expansion transaction.",
  }),
  makeComparable({
    id: "comp-cartago-paraiso-urban",
    title: "Paraiso Urban Services Lot",
    province: "Cartago",
    canton: "Paraiso",
    district: "Paraiso",
    coordinates: { lat: 9.8388, lng: -83.8668 },
    propertyType: "urban lot",
    landSizeM2: 950,
    pricePerM2: 225,
    landUse: "Urban services",
    similarityScore: 63,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Smaller urban benchmark for Cartago regional towns.",
  }),
  makeComparable({
    id: "comp-nosara-eco-lodge",
    title: "Nosara Eco-Lodge Parcel",
    province: "Guanacaste",
    canton: "Nicoya",
    district: "Nosara",
    coordinates: { lat: 9.9816, lng: -85.6525 },
    propertyType: "hospitality land",
    landSizeM2: 5200,
    pricePerM2: 485,
    landUse: "Eco-hospitality",
    similarityScore: 89,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Wellness hospitality comp with road and water constraints noted.",
  }),
  makeComparable({
    id: "comp-nosara-guiones-villas",
    title: "Guiones Villas Development Land",
    province: "Guanacaste",
    canton: "Nicoya",
    district: "Nosara",
    coordinates: { lat: 9.9458, lng: -85.6631 },
    propertyType: "tourism development land",
    landSizeM2: 2400,
    pricePerM2: 695,
    landUse: "Tourism residential",
    similarityScore: 84,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Premium Guiones demand with smaller parcel size.",
  }),
  makeComparable({
    id: "comp-nosara-samara-ridge",
    title: "Samara Ridge Retreat Land",
    province: "Guanacaste",
    canton: "Nicoya",
    district: "Samara",
    coordinates: { lat: 9.8822, lng: -85.5287 },
    propertyType: "mountain eco-lot",
    landSizeM2: 7400,
    pricePerM2: 285,
    landUse: "Eco-retreat",
    similarityScore: 68,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Regional coastal ridge lifestyle reference.",
  }),
  makeComparable({
    id: "comp-nosara-ostional-edge",
    title: "Ostional Conservation Edge Lot",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Ostional",
    coordinates: { lat: 9.9961, lng: -85.7008 },
    propertyType: "mountain eco-lot",
    landSizeM2: 9800,
    pricePerM2: 210,
    landUse: "Low-density eco-residential",
    similarityScore: 61,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Conservation adjacency lowers development intensity.",
  }),
  makeComparable({
    id: "comp-la-fortuna-lodge-site",
    title: "La Fortuna Lodge Site",
    province: "Alajuela",
    canton: "San Carlos",
    district: "La Fortuna",
    coordinates: { lat: 10.4709, lng: -84.6451 },
    propertyType: "hospitality land",
    landSizeM2: 6400,
    pricePerM2: 255,
    landUse: "Tourism lodging",
    similarityScore: 90,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Volcano-view lodging site with strong tourism fundamentals.",
  }),
  makeComparable({
    id: "comp-la-fortuna-arenal-view",
    title: "Arenal View Eco-Lot",
    province: "Alajuela",
    canton: "San Carlos",
    district: "La Fortuna",
    coordinates: { lat: 10.4818, lng: -84.6684 },
    propertyType: "mountain eco-lot",
    landSizeM2: 8600,
    pricePerM2: 135,
    landUse: "Eco-residential",
    similarityScore: 72,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Larger low-density parcel with tourism appeal.",
  }),
  makeComparable({
    id: "comp-la-fortuna-el-tanque",
    title: "El Tanque Tourism Parcel",
    province: "Alajuela",
    canton: "San Carlos",
    district: "La Fortuna",
    coordinates: { lat: 10.4438, lng: -84.6056 },
    propertyType: "tourism development land",
    landSizeM2: 4200,
    pricePerM2: 185,
    landUse: "Tourism services",
    similarityScore: 75,
    saleStatus: "Listed",
    sourceType: "Internal estimate",
    notes: "Tourism support land outside the town center.",
  }),
  makeComparable({
    id: "comp-la-fortuna-muelle-commercial",
    title: "Muelle Commercial Service Lot",
    province: "Alajuela",
    canton: "San Carlos",
    district: "Muelle",
    coordinates: { lat: 10.4784, lng: -84.5482 },
    propertyType: "commercial corner",
    landSizeM2: 2300,
    pricePerM2: 145,
    landUse: "Regional services",
    similarityScore: 57,
    saleStatus: "Sold",
    sourceType: "Market listing",
    notes: "Service-commercial reference with weaker tourism premium.",
  }),
  makeComparable({
    id: "comp-rohrmoser-embassy-corridor",
    title: "Rohrmoser Embassy Corridor Lot",
    province: "San Jose",
    canton: "San Jose",
    district: "Pavas",
    coordinates: { lat: 9.9421, lng: -84.1144 },
    propertyType: "urban lot",
    landSizeM2: 980,
    pricePerM2: 1140,
    landUse: "High-density residential",
    similarityScore: 88,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Premium infill with embassy corridor demand.",
  }),
  makeComparable({
    id: "comp-rohrmoser-sabana-norte",
    title: "Sabana Norte Redevelopment Site",
    province: "San Jose",
    canton: "San Jose",
    district: "Mata Redonda",
    coordinates: { lat: 9.9371, lng: -84.1049 },
    propertyType: "mixed-use parcel",
    landSizeM2: 1350,
    pricePerM2: 960,
    landUse: "Residential-commercial mixed use",
    similarityScore: 84,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Dense redevelopment reference with strong transit and park adjacency.",
  }),
  makeComparable({
    id: "comp-rohrmoser-pavas-service",
    title: "Pavas Mixed-Use Service Parcel",
    province: "San Jose",
    canton: "San Jose",
    district: "Pavas",
    coordinates: { lat: 9.9507, lng: -84.1321 },
    propertyType: "commercial corner",
    landSizeM2: 1680,
    pricePerM2: 685,
    landUse: "Commercial services",
    similarityScore: 69,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "More service-oriented than premium residential infill.",
  }),
  makeComparable({
    id: "comp-rohrmoser-nunciatura-corner",
    title: "Nunciatura Residential Corner",
    province: "San Jose",
    canton: "San Jose",
    district: "Mata Redonda",
    coordinates: { lat: 9.9364, lng: -84.1093 },
    propertyType: "residential development land",
    landSizeM2: 760,
    pricePerM2: 1280,
    landUse: "Premium residential",
    similarityScore: 81,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Small premium lot supporting upper-end per-meter pricing.",
  }),
  makeComparable({
    id: "comp-san-pedro-student-housing",
    title: "San Pedro Student Housing Lot",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "San Pedro",
    coordinates: { lat: 9.9337, lng: -84.0515 },
    propertyType: "residential development land",
    landSizeM2: 840,
    pricePerM2: 650,
    landUse: "Student housing",
    similarityScore: 92,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Direct university corridor residential development reference.",
  }),
  makeComparable({
    id: "comp-san-pedro-los-yoses",
    title: "Los Yoses Redevelopment Site",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "San Pedro",
    coordinates: { lat: 9.9307, lng: -84.0643 },
    propertyType: "mixed-use parcel",
    landSizeM2: 1120,
    pricePerM2: 815,
    landUse: "Mixed-use redevelopment",
    similarityScore: 82,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Higher-priced mixed-use reference near cultural amenities.",
  }),
  makeComparable({
    id: "comp-san-pedro-sabanilla-infill",
    title: "Sabanilla Infill Parcel",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "Sabanilla",
    coordinates: { lat: 9.9362, lng: -84.0369 },
    propertyType: "urban lot",
    landSizeM2: 940,
    pricePerM2: 545,
    landUse: "Urban residential",
    similarityScore: 76,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Residential infill benchmark with student rental demand.",
  }),
  makeComparable({
    id: "comp-san-pedro-barrio-escalante",
    title: "Barrio Escalante Commercial Corner",
    province: "San Jose",
    canton: "San Jose",
    district: "Carmen",
    coordinates: { lat: 9.9367, lng: -84.0615 },
    propertyType: "commercial corner",
    landSizeM2: 620,
    pricePerM2: 940,
    landUse: "Restaurant and services",
    similarityScore: 67,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "High price small-lot commercial reference.",
  }),
  makeComparable({
    id: "comp-lindora-commercial-frontage",
    title: "Lindora Commercial Frontage",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Lindora",
    coordinates: { lat: 9.9495, lng: -84.1891 },
    propertyType: "commercial corner",
    landSizeM2: 1980,
    pricePerM2: 780,
    landUse: "Retail and office services",
    similarityScore: 88,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Premium west-side frontage with strong corporate demand.",
  }),
  makeComparable({
    id: "comp-lindora-flex-site",
    title: "Lindora Flex-Site Parcel",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Lindora",
    coordinates: { lat: 9.9558, lng: -84.1849 },
    propertyType: "logistics parcel",
    landSizeM2: 4100,
    pricePerM2: 560,
    landUse: "Flex industrial-services",
    similarityScore: 86,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Comparable flex service lot near corporate parks.",
  }),
  makeComparable({
    id: "comp-belen-corporate-corridor",
    title: "Belen Corporate Corridor Lot",
    province: "Heredia",
    canton: "Belen",
    district: "La Ribera",
    coordinates: { lat: 9.9882, lng: -84.1816 },
    propertyType: "mixed-use parcel",
    landSizeM2: 2460,
    pricePerM2: 585,
    landUse: "Corporate corridor services",
    similarityScore: 80,
    saleStatus: "Listed",
    sourceType: "Broker record",
    notes: "Office and service demand near airport and business parks.",
  }),
  makeComparable({
    id: "comp-belen-cariari-service",
    title: "Cariari Service Parcel",
    province: "Heredia",
    canton: "Belen",
    district: "Asuncion",
    coordinates: { lat: 9.9796, lng: -84.1544 },
    propertyType: "commercial corner",
    landSizeM2: 1520,
    pricePerM2: 640,
    landUse: "Hotel and office support services",
    similarityScore: 78,
    saleStatus: "Sold",
    sourceType: "Internal estimate",
    notes: "Service-commercial benchmark near hotel cluster.",
  }),
  makeComparable({
    id: "comp-belen-warehouse-edge",
    title: "Belen Warehouse Edge",
    province: "Heredia",
    canton: "Belen",
    district: "La Ribera",
    coordinates: { lat: 9.9849, lng: -84.1906 },
    propertyType: "industrial lot",
    landSizeM2: 5600,
    pricePerM2: 415,
    landUse: "Light industrial and warehousing",
    similarityScore: 82,
    saleStatus: "Pending",
    sourceType: "Market listing",
    notes: "Airport-connected industrial support land.",
  }),
  makeComparable({
    id: "comp-belen-ribera-residential",
    title: "La Ribera Residential Infill",
    province: "Heredia",
    canton: "Belen",
    district: "La Ribera",
    coordinates: { lat: 9.9815, lng: -84.1781 },
    propertyType: "residential development land",
    landSizeM2: 1280,
    pricePerM2: 455,
    landUse: "Residential infill",
    similarityScore: 65,
    saleStatus: "Listed",
    sourceType: "Market listing",
    notes: "Residential alternative use comp near corporate corridor.",
  }),
];
