import { comparableProperties } from "./comparables";

function makeTags(...values) {
  return [...new Set(values.map((value) => String(value || "").trim()).filter(Boolean))];
}

const coreProperties = [
  {
    id: "escazu-mixed-use-corner",
    name: "Escazu Mixed-Use Corner",
    title: "Escazu Mixed-Use Corner",
    province: "San Jose",
    canton: "Escazu",
    district: "San Rafael",
    address: "San Rafael de Escazu, near Multiplaza and Ruta 27",
    latitude: 9.9362,
    longitude: -84.1426,
    coordinates: { lat: 9.9362, lng: -84.1426 },
    propertyType: "Commercial corner",
    landSize: 1850,
    landSizeM2: 1850,
    ownerPrice: 1850000,
    marketPrice: 1942500,
    appraisalPrice: 1572500,
    pricePerM2: 1000,
    landUse: "Mixed-use commercial corridor",
    servicesAvailable: "Water, electricity, sewer, fiber internet, public transport, private services nearby",
    roadAccess: "Paved public road with high commercial exposure",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 91,
    liquidityScore: 88,
    riskScore: 24,
    zoningScore: 90,
    zoningFit: 90,
    infrastructureScore: 94,
    brokerAssigned: "maria-alfaro",
    tags: ["San Jose", "Escazu", "Commercial corner"],
    scoreExplanation:
      "Premium infill parcel with strong access to affluent demand, private services, and commercial footfall.",
    ownerAlignment:
      "Owner price is slightly below the current market estimate, leaving room for investor upside if due diligence confirms access and parking capacity.",
    photos: ["Satellite view", "Street frontage", "Adjacent lots", "Access road"],
    parcelPlan: "SJ-ESC-40518 parcel plan placeholder",
    parcel: {
      registryId: "SJ-ESC-40518",
      frontage: "42 m",
      depth: "46 m",
      coverage: "70% max coverage",
    },
    nearbyServices: [
      { name: "Ruta 27 access", category: "Transit", distance: "0.8 km", note: "Regional highway connection" },
      { name: "Multiplaza Escazu", category: "Retail", distance: "1.1 km", note: "Major commercial anchor" },
      { name: "CIMA Hospital", category: "Health", distance: "1.4 km", note: "Premium healthcare cluster" },
      { name: "International schools", category: "Education", distance: "2.8 km", note: "Family demand driver" },
    ],
    notes: [
      {
        author: "Analyst",
        date: "May 2026",
        text: "Premium infill location with strong commercial footprint. Access via Ruta 27 reduces logistics friction for mixed-use concepts.",
      },
      {
        author: "Maria Alfaro",
        date: "May 2026",
        text: "Validate parking baseline, curb cuts, and municipal frontage requirements before investor presentation.",
      },
    ],
    zoning: {
      classification: "ZC-2 Mixed Commercial",
      permitted: ["Retail commerce", "Commercial offices", "Upper-floor residential", "Medical services"],
      restrictions: ["Max height: 6 floors", "Front setback: 3 m", "Side setback: 2 m"],
    },
    risks: [
      "Entry price requires disciplined absorption assumptions.",
      "Traffic congestion may affect access design and parking requirements.",
      "Comparable transactions vary by frontage quality.",
    ],
  },
  {
    id: "santa-ana-logistics-parcel",
    name: "Santa Ana Logistics Parcel",
    title: "Santa Ana Logistics Parcel",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Pozos",
    address: "Pozos de Santa Ana, west corridor industrial edge",
    latitude: 9.9328,
    longitude: -84.1822,
    coordinates: { lat: 9.9328, lng: -84.1822 },
    propertyType: "Logistics parcel",
    landSize: 4200,
    landSizeM2: 4200,
    ownerPrice: 2100000,
    marketPrice: 2163000,
    appraisalPrice: 1785000,
    pricePerM2: 500,
    landUse: "Light industrial and services",
    servicesAvailable: "Water nearby, electricity nearby, truck access, business services within 2 km",
    roadAccess: "Paved public road near Ruta 27 interchange",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 84,
    liquidityScore: 79,
    riskScore: 31,
    zoningScore: 86,
    zoningFit: 86,
    infrastructureScore: 90,
    brokerAssigned: "diego-vargas",
    tags: ["San Jose", "Santa Ana", "Logistics"],
    scoreExplanation:
      "Well-positioned land for last-mile logistics, service retail, or flex warehouse near the west-side growth corridor.",
    ownerAlignment:
      "Owner price is close to market support, with a modest premium justified by lot size and corridor access.",
    photos: ["Satellite view", "Warehouse context", "Route access", "Utility edge"],
    parcelPlan: "SJ-STA-88402 parcel plan placeholder",
    parcel: {
      registryId: "SJ-STA-88402",
      frontage: "58 m",
      depth: "72 m",
      coverage: "60% max coverage",
    },
    nearbyServices: [
      { name: "Lindora business district", category: "Infrastructure", distance: "1.9 km", note: "Office and service cluster" },
      { name: "Ruta 27 interchange", category: "Transit", distance: "1.5 km", note: "Distribution advantage" },
      { name: "Forum business parks", category: "Infrastructure", distance: "3.1 km", note: "Corporate demand node" },
      { name: "Automercado Lindora", category: "Retail", distance: "2.2 km", note: "Consumer traffic signal" },
    ],
    notes: [
      {
        author: "Analyst",
        date: "May 2026",
        text: "Strong logistics positioning near the Lindora business district. Lot size supports phased warehouse development.",
      },
      {
        author: "Diego Vargas",
        date: "May 2026",
        text: "Truck access via Route 27 interchange confirmed at 1.5 km. Visit should verify frontage quality and peak-hour access.",
      },
    ],
    zoning: {
      classification: "ZI-1 Light Industrial",
      permitted: ["Warehousing", "Light manufacturing", "Distribution", "Industrial services"],
      restrictions: ["Max warehouse height: 12 m", "Front setback: 5 m", "Green buffer: 10 m"],
    },
    risks: [
      "Utility capacity should be validated before design commitments.",
      "Truck access and neighborhood compatibility require review.",
      "Demand profile is less premium than Escazu office-retail nodes.",
    ],
  },
  {
    id: "heredia-student-housing-site",
    name: "Heredia Student Housing Site",
    title: "Heredia Student Housing Site",
    province: "Heredia",
    canton: "Heredia",
    district: "Mercedes",
    address: "Mercedes, Heredia, near Universidad Nacional",
    latitude: 10.0024,
    longitude: -84.1161,
    coordinates: { lat: 10.0024, lng: -84.1161 },
    propertyType: "Residential development land",
    landSize: 960,
    landSizeM2: 960,
    ownerPrice: 585000,
    marketPrice: 609000,
    appraisalPrice: 497250,
    pricePerM2: 609,
    landUse: "Medium-density residential",
    servicesAvailable: "Water, electricity, bus routes, train station nearby, university demand",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 78,
    liquidityScore: 82,
    riskScore: 36,
    zoningScore: 77,
    zoningFit: 77,
    infrastructureScore: 76,
    brokerAssigned: "ana-campos",
    tags: ["Heredia", "Student housing", "Redevelopment"],
    scoreExplanation:
      "Compact redevelopment opportunity supported by student demand, walkability, and attainable entry pricing.",
    ownerAlignment:
      "Owner price is below the market estimate, but density and parking constraints drive the risk review.",
    photos: ["Satellite view", "Neighborhood edge", "Transit route", "Street access"],
    parcelPlan: "HD-MER-12991 parcel plan placeholder",
    parcel: {
      registryId: "HD-MER-12991",
      frontage: "31 m",
      depth: "30 m",
      coverage: "Medium density residential",
    },
    nearbyServices: [
      { name: "Universidad Nacional", category: "Education", distance: "1.3 km", note: "Primary demand driver" },
      { name: "Heredia train station", category: "Transit", distance: "1.8 km", note: "Commuter access" },
      { name: "Hospital San Vicente", category: "Health", distance: "2.4 km", note: "Civic service anchor" },
      { name: "Paseo de las Flores", category: "Retail", distance: "3.5 km", note: "Regional shopping node" },
    ],
    notes: [
      {
        author: "Analyst",
        date: "May 2026",
        text: "Walkable service density supports the rental story. Parking constraints need early resolution in design phase.",
      },
      {
        author: "Ana Campos",
        date: "May 2026",
        text: "Broker package should frame this as student housing with conservative parking and unit-count assumptions.",
      },
    ],
    zoning: {
      classification: "ZR-3 Medium Residential",
      permitted: ["Multi-family housing", "Student residences", "Neighborhood retail", "Professional services"],
      restrictions: ["Max height: 4 floors", "Parking: 1 space per unit", "Front setback: 2 m"],
    },
    risks: [
      "Parking constraints may limit unit density.",
      "Rental upside depends on permitting and product quality.",
      "Neighborhood engagement should happen before design lock.",
    ],
  },
  {
    id: "tamarindo-hospitality-lot",
    name: "Tamarindo Hospitality Lot",
    title: "Tamarindo Hospitality Lot",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Tamarindo",
    address: "Tamarindo beach corridor, Santa Cruz",
    latitude: 10.2993,
    longitude: -85.8371,
    coordinates: { lat: 10.2993, lng: -85.8371 },
    propertyType: "Hospitality land",
    landSize: 2400,
    landSizeM2: 2400,
    ownerPrice: 1320000,
    marketPrice: 1384000,
    appraisalPrice: 1122000,
    pricePerM2: 550,
    landUse: "Tourism commercial",
    servicesAvailable: "Electricity, road access, restaurant demand, water availability pending",
    roadAccess: "Paved public road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 73,
    liquidityScore: 70,
    riskScore: 44,
    zoningScore: 74,
    zoningFit: 74,
    infrastructureScore: 68,
    brokerAssigned: "carlos-rojas",
    tags: ["Guanacaste", "Hospitality", "Tourism"],
    scoreExplanation:
      "Tourism-led upside with boutique lodging potential, balanced by infrastructure and seasonality risk.",
    ownerAlignment:
      "Owner price is within the tourism corridor range, but infrastructure checks should drive negotiation posture.",
    photos: ["Satellite view", "Beach corridor", "Access road", "Adjacent parcels"],
    parcelPlan: "GU-SCZ-77401 parcel plan placeholder",
    parcel: {
      registryId: "GU-SCZ-77401",
      frontage: "45 m",
      depth: "53 m",
      coverage: "40% max coverage",
    },
    nearbyServices: [
      { name: "Tamarindo beach", category: "Infrastructure", distance: "0.9 km", note: "Tourism anchor" },
      { name: "Route 152 access", category: "Transit", distance: "0.5 km", note: "Local connectivity" },
      { name: "Restaurants and surf schools", category: "Retail", distance: "0.7 km", note: "Visitor activity" },
      { name: "Tamarindo Airport", category: "Transit", distance: "4.1 km", note: "Regional air access" },
    ],
    notes: [
      {
        author: "Carlos Rojas",
        date: "May 2026",
        text: "Strong long-term fundamentals if entry timing is right. Water availability and seasonal demand need early technical diligence.",
      },
    ],
    zoning: {
      classification: "ZT-2 Tourism Commercial",
      permitted: ["Tourist accommodation", "Restaurants", "Villas", "Spa and wellness"],
      restrictions: ["Max height: 3 floors", "Maritime setback review", "Water protection: 15 m"],
    },
    risks: [
      "Water availability and infrastructure capacity need early diligence.",
      "Revenue model is exposed to tourism seasonality.",
      "Construction logistics can widen contingency budgets.",
    ],
  },
  {
    id: "curridabat-mixed-use-parcel",
    name: "Curridabat Mixed-Use Parcel",
    title: "Curridabat Mixed-Use Parcel",
    province: "San Jose",
    canton: "Curridabat",
    district: "Granadilla",
    address: "Granadilla, Curridabat, near Pinares medical and retail corridor",
    latitude: 9.9181,
    longitude: -84.0195,
    coordinates: { lat: 9.9181, lng: -84.0195 },
    propertyType: "Mixed-use parcel",
    landSize: 1550,
    landSizeM2: 1550,
    ownerPrice: 1120000,
    marketPrice: 1162500,
    appraisalPrice: 952000,
    pricePerM2: 723,
    landUse: "Medical, retail, and residential services",
    servicesAvailable: "Water, electricity, sewer, fiber, medical and retail demand nearby",
    roadAccess: "Paved public road with east-side corridor visibility",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 81,
    liquidityScore: 77,
    riskScore: 29,
    zoningScore: 84,
    zoningFit: 84,
    infrastructureScore: 88,
    brokerAssigned: "laura-mendez",
    tags: ["San Jose", "Curridabat", "Mixed-use"],
    scoreExplanation:
      "East-side mixed-use parcel with strong services demand and a defensible medical-retail positioning story.",
    ownerAlignment:
      "Owner price is close to inferred market support. Comparable evidence should focus on mixed-use and medical corridor parcels.",
    photos: ["Satellite view", "Street frontage", "Adjacent services", "Access road"],
    parcelPlan: "SJ-CUR-55120 parcel plan placeholder",
    parcel: {
      registryId: "SJ-CUR-55120",
      frontage: "36 m",
      depth: "43 m",
      coverage: "65% max coverage",
    },
    nearbyServices: [
      { name: "Pinares retail corridor", category: "Retail", distance: "0.6 km", note: "Consumer and service demand" },
      { name: "Medical offices", category: "Health", distance: "0.8 km", note: "Medical corridor adjacency" },
      { name: "Universidad Autonoma", category: "Education", distance: "2.1 km", note: "Student and staff demand" },
      { name: "Route 2 access", category: "Transit", distance: "1.4 km", note: "East-west connectivity" },
    ],
    notes: [
      {
        author: "Laura Mendez",
        date: "May 2026",
        text: "Position as medical-services mixed-use. Parking and access design will determine final investor fit.",
      },
    ],
    zoning: {
      classification: "ZM-1 Mixed Urban",
      permitted: ["Medical services", "Retail commerce", "Professional offices", "Upper-floor residential"],
      restrictions: ["Traffic impact review may apply", "Parking ratio depends on final use", "Municipal review required"],
    },
    risks: [
      "Final use mix depends on parking feasibility.",
      "Medical corridor comparables vary by visibility.",
      "Access design needs confirmation with municipal criteria.",
    ],
  },
];

function makeActiveProperty(seed) {
  const ownerPrice = Number(seed.ownerPrice);
  const landSize = Number(seed.landSize);
  const pricePerM2 = seed.pricePerM2 || Math.round(ownerPrice / landSize);
  const marketPrice = seed.marketPrice || Math.round(ownerPrice * 1.04);
  const appraisalPrice = seed.appraisalPrice || Math.round(ownerPrice * 0.86);
  const zoningFit = seed.zoningFit || seed.zoningScore || 72;
  const title = seed.title || seed.name;
  const brokerNote = seed.brokerNote || "Broker should verify access, utilities, zoning documentation, and comparable support before presentation.";

  return {
    id: seed.id,
    name: title,
    title,
    province: seed.province,
    canton: seed.canton,
    district: seed.district,
    address: seed.address,
    latitude: seed.coordinates.lat,
    longitude: seed.coordinates.lng,
    coordinates: seed.coordinates,
    propertyType: seed.propertyType,
    landSize,
    landSizeM2: landSize,
    ownerPrice,
    marketPrice,
    appraisalPrice,
    pricePerM2,
    landUse: seed.landUse,
    servicesAvailable: seed.servicesAvailable,
    roadAccess: seed.roadAccess,
    waterAvailability: seed.waterAvailability,
    electricityAvailability: seed.electricityAvailability,
    investmentScore: seed.investmentScore,
    liquidityScore: seed.liquidityScore,
    riskScore: seed.riskScore,
    zoningScore: zoningFit,
    zoningFit,
    infrastructureScore: seed.infrastructureScore,
    brokerAssigned: seed.brokerAssigned,
    tags: makeTags(seed.province, seed.canton, seed.propertyType),
    scoreExplanation: seed.scoreExplanation,
    ownerAlignment: seed.ownerAlignment,
    photos: seed.photos || ["Satellite view", "Street frontage", "Adjacent lots", "Access road"],
    parcelPlan: `${seed.parcel.registryId} parcel plan placeholder`,
    parcel: seed.parcel,
    nearbyServices: seed.nearbyServices,
    notes: [
      {
        author: "Analyst",
        date: "May 2026",
        text: seed.analystNote,
      },
      {
        author: seed.brokerName,
        date: "May 2026",
        text: brokerNote,
      },
    ],
    zoning: {
      classification: seed.zoningClassification,
      permitted: seed.permitted,
      restrictions: seed.restrictions,
    },
    risks: seed.risks,
  };
}

const additionalProperties = [
  makeActiveProperty({
    id: "liberia-airport-service-lot",
    title: "Liberia Airport Service Lot",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Liberia",
    address: "Route to Daniel Oduber airport, near rental car and logistics services",
    coordinates: { lat: 10.5925, lng: -85.5482 },
    propertyType: "Commercial corner",
    landSize: 3700,
    ownerPrice: 1110000,
    landUse: "Airport services and regional retail",
    servicesAvailable: "Water nearby, electricity nearby, paved frontage, airport service demand",
    roadAccess: "Paved public road near airport access",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 82,
    liquidityScore: 77,
    riskScore: 34,
    zoningFit: 79,
    infrastructureScore: 83,
    brokerAssigned: "andres-solis",
    brokerName: "Andres Solis",
    scoreExplanation: "Airport corridor visibility and regional service demand support a strong commercial listing story.",
    ownerAlignment: "Owner price is close to corridor support if access and utilities are confirmed.",
    parcel: { registryId: "GU-LIB-88104", frontage: "64 m", depth: "58 m", coverage: "55% max coverage" },
    nearbyServices: [
      { name: "Daniel Oduber Airport", category: "Transit", distance: "2.4 km", note: "Regional arrival demand" },
      { name: "Route 21", category: "Transit", distance: "0.7 km", note: "Airport corridor access" },
      { name: "Rental car cluster", category: "Retail", distance: "1.1 km", note: "Visitor services" },
      { name: "Liberia center", category: "Infrastructure", distance: "9.2 km", note: "Regional services" },
    ],
    analystNote: "Good airport-linked commercial site. Buyer pool likely includes service retail, car rental, and logistics support.",
    brokerNote: "Confirm right-of-way, signage rules, and water letter before launch.",
    zoningClassification: "Commercial Services Corridor",
    permitted: ["Retail services", "Vehicle services", "Tourism support", "Offices"],
    restrictions: ["Airport corridor signage review", "Setbacks to be confirmed", "Traffic access review may apply"],
    risks: ["Water service confirmation is pending.", "Airport corridor prices vary by frontage quality.", "Traffic access design may affect final use."],
  }),
  makeActiveProperty({
    id: "jaco-beachfront-opportunity",
    title: "Jaco Beachfront Opportunity",
    province: "Puntarenas",
    canton: "Garabito",
    district: "Jaco",
    address: "Central Jaco beachfront, near hotel and restaurant zone",
    coordinates: { lat: 9.6141, lng: -84.6297 },
    propertyType: "Beachfront opportunity",
    landSize: 1750,
    ownerPrice: 1620000,
    landUse: "Tourism commercial",
    servicesAvailable: "Water, electricity, road access, beachfront tourism demand",
    roadAccess: "Paved public road and beach access nearby",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 79,
    liquidityScore: 74,
    riskScore: 41,
    zoningFit: 73,
    infrastructureScore: 80,
    brokerAssigned: "sofia-quesada",
    brokerName: "Sofia Quesada",
    scoreExplanation: "Direct beach exposure creates strong hospitality upside, balanced by coastal due diligence requirements.",
    ownerAlignment: "Owner price is aggressive but plausible for a clean beachfront asset.",
    parcel: { registryId: "PU-GAR-77420", frontage: "32 m", depth: "55 m", coverage: "Tourism review required" },
    nearbyServices: [
      { name: "Jaco beach", category: "Infrastructure", distance: "0.1 km", note: "Tourism anchor" },
      { name: "Hotel and restaurant strip", category: "Retail", distance: "0.3 km", note: "Visitor activity" },
      { name: "Route 34", category: "Transit", distance: "1.2 km", note: "Coastal highway access" },
      { name: "Herradura marina", category: "Infrastructure", distance: "8.6 km", note: "Premium tourism node" },
    ],
    analystNote: "Strong marketing asset for tourism buyers. Concession and coastal regulation review are critical.",
    zoningClassification: "Tourism Commercial Coastal",
    permitted: ["Tourist accommodation", "Restaurants", "Retail services", "Wellness uses"],
    restrictions: ["Coastal concession review", "Environmental setbacks", "Height restrictions may apply"],
    risks: ["Coastal regulation can affect buildable area.", "Tourism demand is seasonal.", "Insurance and construction costs may be elevated."],
  }),
  makeActiveProperty({
    id: "grecia-view-residential-land",
    title: "Grecia View Residential Land",
    province: "Alajuela",
    canton: "Grecia",
    district: "Grecia",
    address: "North Grecia hillside, paved road and valley view",
    coordinates: { lat: 10.0735, lng: -84.3117 },
    propertyType: "Residential development land",
    landSize: 5200,
    ownerPrice: 860000,
    landUse: "Low-density residential",
    servicesAvailable: "Electricity nearby, water nearby, paved road, valley view",
    roadAccess: "Paved public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 72,
    liquidityScore: 68,
    riskScore: 37,
    zoningFit: 75,
    infrastructureScore: 71,
    brokerAssigned: "esteban-mora",
    brokerName: "Esteban Mora",
    scoreExplanation: "Family residential demand and view premium support value if slope and water are confirmed.",
    ownerAlignment: "Owner price is reasonable for a view parcel with confirmed utilities.",
    parcel: { registryId: "AL-GRE-33912", frontage: "78 m", depth: "67 m", coverage: "Low-density residential" },
    nearbyServices: [
      { name: "Grecia center", category: "Retail", distance: "2.7 km", note: "Town services" },
      { name: "Route 118", category: "Transit", distance: "1.1 km", note: "Regional access" },
      { name: "Private schools", category: "Education", distance: "3.5 km", note: "Family demand" },
      { name: "Medical clinic", category: "Health", distance: "2.9 km", note: "Local healthcare" },
    ],
    analystNote: "Good suburban residential candidate. Slope, drainage, and water connection are diligence priorities.",
    zoningClassification: "Residential Expansion",
    permitted: ["Single-family housing", "Small gated community", "Recreational amenities"],
    restrictions: ["Slope analysis required", "Water letter needed", "Road improvements may apply"],
    risks: ["Buildability depends on slope.", "Absorption is slower than GAM core.", "Water connection timing may affect launch."],
  }),
  makeActiveProperty({
    id: "alajuela-airport-logistics-parcel",
    title: "Alajuela Airport Logistics Parcel",
    province: "Alajuela",
    canton: "Alajuela",
    district: "Rio Segundo",
    address: "Rio Segundo, airport logistics corridor with Route 1 access",
    coordinates: { lat: 9.9993, lng: -84.2099 },
    propertyType: "Logistics parcel",
    landSize: 6400,
    ownerPrice: 2848000,
    landUse: "Airport logistics",
    servicesAvailable: "Water, three-phase electricity nearby, truck access, airport services",
    roadAccess: "Paved public road near airport and Route 1",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 86,
    liquidityScore: 81,
    riskScore: 28,
    zoningFit: 85,
    infrastructureScore: 92,
    brokerAssigned: "oscar-benavides",
    brokerName: "Oscar Benavides",
    scoreExplanation: "Airport adjacency and logistics demand create strong institutional buyer interest.",
    ownerAlignment: "Owner price is supported if industrial utility capacity is documented.",
    parcel: { registryId: "AL-ALJ-90214", frontage: "82 m", depth: "78 m", coverage: "65% max coverage" },
    nearbyServices: [
      { name: "SJO Airport", category: "Transit", distance: "1.9 km", note: "Air cargo proximity" },
      { name: "Route 1", category: "Transit", distance: "0.9 km", note: "Regional logistics access" },
      { name: "Coyol industrial cluster", category: "Infrastructure", distance: "8.7 km", note: "Industrial demand" },
      { name: "Airport hotels", category: "Retail", distance: "2.2 km", note: "Service demand" },
    ],
    analystNote: "High-conviction logistics parcel. Utility capacity and truck access are the key validation points.",
    zoningClassification: "Airport Logistics",
    permitted: ["Warehousing", "Distribution", "Industrial services", "Vehicle services"],
    restrictions: ["Traffic study may apply", "Airport height review", "Environmental compliance required"],
    risks: ["Traffic access approvals may affect design.", "Utility capacity must be documented.", "Industrial buyer underwriting is rate-sensitive."],
  }),
  makeActiveProperty({
    id: "cartago-industrial-support-lot",
    title: "Cartago Industrial Support Lot",
    province: "Cartago",
    canton: "Cartago",
    district: "Oriental",
    address: "Cartago industrial edge, access to regional road",
    coordinates: { lat: 9.8669, lng: -83.9197 },
    propertyType: "Industrial lot",
    landSize: 5400,
    ownerPrice: 1430000,
    landUse: "Industrial support",
    servicesAvailable: "Water nearby, electricity nearby, truck access, industrial services",
    roadAccess: "Paved public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 77,
    liquidityScore: 70,
    riskScore: 33,
    zoningFit: 82,
    infrastructureScore: 79,
    brokerAssigned: "valeria-castro",
    brokerName: "Valeria Castro",
    scoreExplanation: "Cartago industrial adjacency and regional access support a practical owner listing strategy.",
    ownerAlignment: "Owner price is aligned with regional industrial land evidence.",
    parcel: { registryId: "CA-CRT-55409", frontage: "70 m", depth: "77 m", coverage: "60% max coverage" },
    nearbyServices: [
      { name: "Cartago industrial area", category: "Infrastructure", distance: "0.8 km", note: "Industrial demand" },
      { name: "Route 10", category: "Transit", distance: "1.5 km", note: "Regional access" },
      { name: "Cartago center", category: "Retail", distance: "2.4 km", note: "Labor and services" },
      { name: "TEC campus", category: "Education", distance: "3.8 km", note: "Technical talent" },
    ],
    analystNote: "Solid industrial support site. Target buyers are local manufacturers and service operators.",
    zoningClassification: "Industrial Support",
    permitted: ["Light manufacturing", "Warehousing", "Industrial services", "Workshops"],
    restrictions: ["Noise controls", "Truck access review", "Buffer setbacks may apply"],
    risks: ["Regional industrial liquidity is thinner than GAM west.", "Permitted use must be confirmed.", "Road capacity may constrain heavy operations."],
  }),
  makeActiveProperty({
    id: "nosara-eco-lodge-parcel",
    title: "Nosara Eco-Lodge Parcel",
    province: "Guanacaste",
    canton: "Nicoya",
    district: "Nosara",
    address: "Nosara ridge road, 12 minutes from Guiones",
    coordinates: { lat: 9.9816, lng: -85.6525 },
    propertyType: "Hospitality land",
    landSize: 5400,
    ownerPrice: 2620000,
    landUse: "Eco-hospitality",
    servicesAvailable: "Electricity nearby, private water source reported, gravel road access",
    roadAccess: "Gravel public road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 76,
    liquidityScore: 67,
    riskScore: 46,
    zoningFit: 72,
    infrastructureScore: 63,
    brokerAssigned: "marco-hidalgo",
    brokerName: "Marco Hidalgo",
    scoreExplanation: "Wellness tourism supports premium upside, but road and water risk require cautious underwriting.",
    ownerAlignment: "Owner price needs strong water documentation and buildable-area confirmation.",
    parcel: { registryId: "GU-NIC-44021", frontage: "96 m", depth: "58 m", coverage: "Eco-tourism review" },
    nearbyServices: [
      { name: "Playa Guiones", category: "Infrastructure", distance: "7.8 km", note: "Wellness tourism anchor" },
      { name: "Nosara airport", category: "Transit", distance: "4.6 km", note: "Regional access" },
      { name: "Yoga and wellness cluster", category: "Retail", distance: "6.2 km", note: "Visitor demand" },
      { name: "Nicoya services", category: "Infrastructure", distance: "34 km", note: "Regional services" },
    ],
    analystNote: "Tourism story is strong, but diligence should lead with water, road seasonality, and environmental constraints.",
    zoningClassification: "Eco-Tourism Low Density",
    permitted: ["Eco-lodging", "Wellness retreat", "Low-density villas", "Conservation amenities"],
    restrictions: ["Water source validation", "Environmental review", "Road improvement may be needed"],
    risks: ["Water proof is unresolved.", "Road conditions vary seasonally.", "Construction logistics may widen budgets."],
  }),
  makeActiveProperty({
    id: "la-fortuna-lodge-site",
    title: "La Fortuna Lodge Site",
    province: "Alajuela",
    canton: "San Carlos",
    district: "La Fortuna",
    address: "La Fortuna, volcano view corridor west of town",
    coordinates: { lat: 10.4709, lng: -84.6451 },
    propertyType: "Hospitality land",
    landSize: 6400,
    ownerPrice: 1640000,
    landUse: "Tourism lodging",
    servicesAvailable: "Water nearby, electricity nearby, tourism services, paved access",
    roadAccess: "Paved public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 80,
    liquidityScore: 73,
    riskScore: 35,
    zoningFit: 78,
    infrastructureScore: 77,
    brokerAssigned: "paola-jimenez",
    brokerName: "Paola Jimenez",
    scoreExplanation: "Volcano-view positioning and year-round tourism create a strong lodging development story.",
    ownerAlignment: "Owner price is supportable if buildable area and utility letters are confirmed.",
    parcel: { registryId: "AL-SCA-77102", frontage: "88 m", depth: "73 m", coverage: "Tourism lodging review" },
    nearbyServices: [
      { name: "La Fortuna center", category: "Retail", distance: "3.1 km", note: "Tourism services" },
      { name: "Arenal volcano views", category: "Infrastructure", distance: "Visible", note: "Demand driver" },
      { name: "Hot springs corridor", category: "Retail", distance: "4.8 km", note: "Hospitality demand" },
      { name: "Route 142", category: "Transit", distance: "0.8 km", note: "Regional access" },
    ],
    analystNote: "High-quality tourism candidate. Comparable set should emphasize lodge sites, not agricultural land.",
    zoningClassification: "Tourism Development",
    permitted: ["Lodging", "Restaurant", "Wellness amenities", "Low-density villas"],
    restrictions: ["Setbacks to waterways", "Environmental review", "Access design review"],
    risks: ["Buildable area must be verified.", "Tourism revenue is seasonal.", "Infrastructure connection timing may affect launch."],
  }),
  makeActiveProperty({
    id: "rohrmoser-embassy-corridor-lot",
    title: "Rohrmoser Embassy Corridor Lot",
    province: "San Jose",
    canton: "San Jose",
    district: "Pavas",
    address: "Rohrmoser, near embassy corridor and La Sabana access",
    coordinates: { lat: 9.9421, lng: -84.1144 },
    propertyType: "Urban lot",
    landSize: 980,
    ownerPrice: 1120000,
    landUse: "High-density residential",
    servicesAvailable: "Water, electricity, sewer, fiber, mature urban services",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 83,
    liquidityScore: 86,
    riskScore: 27,
    zoningFit: 80,
    infrastructureScore: 91,
    brokerAssigned: "gabriel-arias",
    brokerName: "Gabriel Arias",
    scoreExplanation: "Premium infill location with excellent services and strong redevelopment buyer liquidity.",
    ownerAlignment: "Owner price reflects premium district expectations; density proof will matter.",
    parcel: { registryId: "SJ-PAV-66031", frontage: "28 m", depth: "35 m", coverage: "High-density urban" },
    nearbyServices: [
      { name: "La Sabana park", category: "Infrastructure", distance: "1.1 km", note: "Amenity driver" },
      { name: "Embassy corridor", category: "Infrastructure", distance: "0.6 km", note: "Premium demand" },
      { name: "Boulevard Rohrmoser", category: "Retail", distance: "0.4 km", note: "Local services" },
      { name: "Route 1 access", category: "Transit", distance: "1.8 km", note: "Regional access" },
    ],
    analystNote: "Strong urban infill asset. Parking and density assumptions will drive underwriting.",
    zoningClassification: "High-Density Residential",
    permitted: ["Apartments", "Professional offices", "Neighborhood services"],
    restrictions: ["Parking ratio applies", "Height limits by zoning", "Setbacks to be confirmed"],
    risks: ["Small lot may constrain parking.", "Premium pricing narrows buyer pool.", "Density assumptions need municipal support."],
  }),
  makeActiveProperty({
    id: "san-pedro-student-housing-lot",
    title: "San Pedro Student Housing Lot",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "San Pedro",
    address: "San Pedro, walking distance to university corridor",
    coordinates: { lat: 9.9337, lng: -84.0515 },
    propertyType: "Residential development land",
    landSize: 840,
    ownerPrice: 548000,
    landUse: "Student housing",
    servicesAvailable: "Water, electricity, bus routes, train access nearby, university demand",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 75,
    liquidityScore: 79,
    riskScore: 38,
    zoningFit: 74,
    infrastructureScore: 82,
    brokerAssigned: "natalia-leiva",
    brokerName: "Natalia Leiva",
    scoreExplanation: "University corridor demand supports rental housing, but parking and unit mix require discipline.",
    ownerAlignment: "Owner price is close to student housing support if density is achievable.",
    parcel: { registryId: "SJ-MOC-51022", frontage: "24 m", depth: "35 m", coverage: "Medium-density residential" },
    nearbyServices: [
      { name: "University corridor", category: "Education", distance: "0.8 km", note: "Student demand" },
      { name: "San Pedro Mall", category: "Retail", distance: "1.1 km", note: "Services" },
      { name: "Train station", category: "Transit", distance: "1.6 km", note: "Commuter access" },
      { name: "Bus routes", category: "Transit", distance: "0.2 km", note: "Urban mobility" },
    ],
    analystNote: "Good rental demand story. Needs a careful parking and bedroom-count model.",
    zoningClassification: "Medium-Density Residential",
    permitted: ["Multi-family housing", "Student residences", "Neighborhood retail"],
    restrictions: ["Parking minimums", "Height limit review", "Noise controls may apply"],
    risks: ["Parking may limit density.", "Student housing revenue depends on product quality.", "Neighborhood objections are possible."],
  }),
  makeActiveProperty({
    id: "lindora-commercial-frontage",
    title: "Lindora Commercial Frontage",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Lindora",
    address: "Lindora main commercial corridor, near office and retail anchors",
    coordinates: { lat: 9.9495, lng: -84.1891 },
    propertyType: "Commercial corner",
    landSize: 1980,
    ownerPrice: 1540000,
    landUse: "Retail and office services",
    servicesAvailable: "Water, electricity, fiber, paved frontage, corporate demand",
    roadAccess: "Paved public road with high visibility",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 87,
    liquidityScore: 82,
    riskScore: 26,
    zoningFit: 84,
    infrastructureScore: 90,
    brokerAssigned: "renato-fonseca",
    brokerName: "Renato Fonseca",
    scoreExplanation: "Premium west-side frontage with strong office, retail, and services demand.",
    ownerAlignment: "Owner price appears defensible if frontage and access permissions are confirmed.",
    parcel: { registryId: "SJ-STA-78145", frontage: "48 m", depth: "41 m", coverage: "70% max coverage" },
    nearbyServices: [
      { name: "Lindora retail corridor", category: "Retail", distance: "0.2 km", note: "Consumer activity" },
      { name: "Forum business parks", category: "Infrastructure", distance: "2.0 km", note: "Corporate demand" },
      { name: "Ruta 27", category: "Transit", distance: "1.4 km", note: "Regional access" },
      { name: "Private schools", category: "Education", distance: "2.8 km", note: "Family demand" },
    ],
    analystNote: "High-quality frontage asset. Best buyer pool is service retail or office-support use.",
    zoningClassification: "Commercial Corridor",
    permitted: ["Retail", "Offices", "Restaurants", "Medical services"],
    restrictions: ["Access design review", "Parking requirements", "Setbacks to be confirmed"],
    risks: ["Access design affects value.", "Premium pricing requires strong comparables.", "Traffic congestion may affect operations."],
  }),
  makeActiveProperty({
    id: "belen-corporate-corridor-lot",
    title: "Belen Corporate Corridor Lot",
    province: "Heredia",
    canton: "Belen",
    district: "La Ribera",
    address: "La Ribera de Belen, near business hotels and office parks",
    coordinates: { lat: 9.9882, lng: -84.1816 },
    propertyType: "Mixed-use parcel",
    landSize: 2460,
    ownerPrice: 1440000,
    landUse: "Corporate corridor services",
    servicesAvailable: "Water, electricity, fiber, airport access, corporate services",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 80,
    liquidityScore: 78,
    riskScore: 30,
    zoningFit: 81,
    infrastructureScore: 87,
    brokerAssigned: "isabel-nunez",
    brokerName: "Isabel Nunez",
    scoreExplanation: "Corporate corridor location supports office-service, hotel support, and airport-linked demand.",
    ownerAlignment: "Owner price is aligned with business park support land if zoning confirms mixed use.",
    parcel: { registryId: "HE-BEL-34219", frontage: "42 m", depth: "59 m", coverage: "65% max coverage" },
    nearbyServices: [
      { name: "Business hotels", category: "Infrastructure", distance: "0.9 km", note: "Corporate demand" },
      { name: "Cariari office cluster", category: "Infrastructure", distance: "2.1 km", note: "Office support" },
      { name: "SJO Airport", category: "Transit", distance: "5.5 km", note: "Airport access" },
      { name: "Route 1", category: "Transit", distance: "1.7 km", note: "Regional access" },
    ],
    analystNote: "Balanced corporate services asset. Works as service retail, office support, or light mixed-use.",
    zoningClassification: "Corporate Corridor Mixed Use",
    permitted: ["Offices", "Retail services", "Hotel support", "Light services"],
    restrictions: ["Traffic review may apply", "Parking minimums", "Municipal use confirmation required"],
    risks: ["Use mix depends on parking feasibility.", "Corporate demand is sensitive to absorption.", "Comparable set varies by business park proximity."],
  }),
  makeActiveProperty({
    id: "atenas-ridge-eco-lot",
    title: "Atenas Ridge Eco-Lot",
    province: "Alajuela",
    canton: "Atenas",
    district: "Atenas",
    address: "Atenas ridge road, valley and mountain views",
    coordinates: { lat: 9.9798, lng: -84.3791 },
    propertyType: "Mountain eco-lot",
    landSize: 6400,
    ownerPrice: 930000,
    landUse: "Eco-residential",
    servicesAvailable: "Electricity nearby, water source to confirm, private road access",
    roadAccess: "Private road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 64,
    liquidityScore: 58,
    riskScore: 49,
    zoningFit: 67,
    infrastructureScore: 55,
    brokerAssigned: "manuel-cordero",
    brokerName: "Manuel Cordero",
    scoreExplanation: "Lifestyle demand exists, but water, slope, and private road risk limit immediate liquidity.",
    ownerAlignment: "Owner price requires strong view premium and infrastructure proof.",
    parcel: { registryId: "AL-ATE-11920", frontage: "92 m", depth: "70 m", coverage: "Low-density eco-residential" },
    nearbyServices: [
      { name: "Atenas center", category: "Retail", distance: "5.4 km", note: "Town services" },
      { name: "Route 27", category: "Transit", distance: "9.8 km", note: "Regional access" },
      { name: "View corridor", category: "Infrastructure", distance: "On-site", note: "Lifestyle premium" },
      { name: "Local clinics", category: "Health", distance: "6.0 km", note: "Basic services" },
    ],
    analystNote: "Good lifestyle asset but should be positioned carefully until water and road status are documented.",
    zoningClassification: "Low-Density Eco Residential",
    permitted: ["Single-family homes", "Eco-retreat", "Small hospitality use"],
    restrictions: ["Water proof required", "Slope study required", "Road maintenance agreement needed"],
    risks: ["Water proof is unresolved.", "Private road limits liquidity.", "Slope may reduce buildable area."],
  }),
  makeActiveProperty({
    id: "papagayo-tourism-support-parcel",
    title: "Papagayo Tourism Support Parcel",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Nacascolo",
    address: "Access road to Papagayo tourism corridor",
    coordinates: { lat: 10.6284, lng: -85.6472 },
    propertyType: "Tourism development land",
    landSize: 5200,
    ownerPrice: 1360000,
    landUse: "Tourism support services",
    servicesAvailable: "Electricity nearby, paved road access, tourism corridor demand",
    roadAccess: "Paved public road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 74,
    liquidityScore: 66,
    riskScore: 43,
    zoningFit: 75,
    infrastructureScore: 72,
    brokerAssigned: "andres-solis",
    brokerName: "Andres Solis",
    scoreExplanation: "Papagayo corridor exposure supports tourism-support uses if water and access rights are confirmed.",
    ownerAlignment: "Owner price is reasonable for corridor support land pending water confirmation.",
    parcel: { registryId: "GU-LIB-44582", frontage: "80 m", depth: "65 m", coverage: "Tourism support review" },
    nearbyServices: [
      { name: "Papagayo resorts", category: "Infrastructure", distance: "11 km", note: "Tourism demand" },
      { name: "Liberia airport", category: "Transit", distance: "23 km", note: "Arrival gateway" },
      { name: "Route 21", category: "Transit", distance: "6.5 km", note: "Regional access" },
      { name: "Marina Papagayo", category: "Retail", distance: "15 km", note: "Premium tourism" },
    ],
    analystNote: "Tourism support land with good long-term fundamentals. Water diligence should lead the review.",
    zoningClassification: "Tourism Support",
    permitted: ["Tourism services", "Small lodging", "Retail support", "Staff housing"],
    restrictions: ["Water letter required", "Environmental review", "Tourism corridor design standards"],
    risks: ["Water may constrain development.", "Tourism cycles affect demand.", "Distance to core resorts affects pricing."],
  }),
  makeActiveProperty({
    id: "tres-rios-mixed-use-corner",
    title: "Tres Rios Mixed-Use Corner",
    province: "Cartago",
    canton: "La Union",
    district: "Tres Rios",
    address: "Tres Rios, near old road to Cartago commercial services",
    coordinates: { lat: 9.9068, lng: -83.9876 },
    propertyType: "Mixed-use parcel",
    landSize: 1620,
    ownerPrice: 700000,
    landUse: "Residential-commercial mixed use",
    servicesAvailable: "Water, electricity, bus route, paved road, neighborhood services",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 76,
    liquidityScore: 72,
    riskScore: 32,
    zoningFit: 78,
    infrastructureScore: 81,
    brokerAssigned: "karla-picado",
    brokerName: "Karla Picado",
    scoreExplanation: "East-side mixed-use corner with practical services demand and accessible price point.",
    ownerAlignment: "Owner price is reasonable if updated parcel plan and zoning letters are clean.",
    parcel: { registryId: "CA-LUN-22018", frontage: "38 m", depth: "43 m", coverage: "60% max coverage" },
    nearbyServices: [
      { name: "Tres Rios center", category: "Retail", distance: "0.8 km", note: "Town services" },
      { name: "Old road to Cartago", category: "Transit", distance: "0.2 km", note: "Commercial exposure" },
      { name: "Schools", category: "Education", distance: "1.5 km", note: "Residential demand" },
      { name: "Curridabat retail", category: "Retail", distance: "4.6 km", note: "Regional demand" },
    ],
    analystNote: "Practical mid-market mixed-use property. Clean documentation will matter for buyer confidence.",
    zoningClassification: "Mixed Urban",
    permitted: ["Retail", "Residential", "Offices", "Professional services"],
    restrictions: ["Updated parcel plan needed", "Parking requirements", "Setbacks to confirm"],
    risks: ["Documentation is incomplete.", "Parking may constrain use.", "Traffic visibility is good but not premium."],
  }),
  makeActiveProperty({
    id: "coyol-industrial-expansion-site",
    title: "Coyol Industrial Expansion Site",
    province: "Alajuela",
    canton: "Alajuela",
    district: "Coyol",
    address: "Coyol industrial corridor, near Route 1 access",
    coordinates: { lat: 9.9928, lng: -84.2503 },
    propertyType: "Industrial lot",
    landSize: 9200,
    ownerPrice: 2860000,
    landUse: "Industrial park support",
    servicesAvailable: "Three-phase electricity, water nearby, truck access, industrial labor pool",
    roadAccess: "Paved public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available and connected",
    investmentScore: 85,
    liquidityScore: 80,
    riskScore: 29,
    zoningFit: 88,
    infrastructureScore: 89,
    brokerAssigned: "oscar-benavides",
    brokerName: "Oscar Benavides",
    scoreExplanation: "Coyol industrial demand and utility access support strong institutional interest.",
    ownerAlignment: "Owner price is consistent with industrial corridor support if zoning is documented.",
    parcel: { registryId: "AL-ALJ-77190", frontage: "105 m", depth: "88 m", coverage: "70% max coverage" },
    nearbyServices: [
      { name: "Coyol industrial park", category: "Infrastructure", distance: "2.1 km", note: "Industrial demand" },
      { name: "Route 1", category: "Transit", distance: "1.6 km", note: "Regional access" },
      { name: "SJO Airport", category: "Transit", distance: "12 km", note: "Air cargo access" },
      { name: "Medical device cluster", category: "Infrastructure", distance: "2.7 km", note: "Institutional demand" },
    ],
    analystNote: "Strong industrial expansion candidate. Utility and access verification should happen before listing.",
    zoningClassification: "Industrial Corridor",
    permitted: ["Manufacturing", "Warehousing", "Distribution", "Industrial services"],
    restrictions: ["Environmental compliance", "Traffic study may apply", "Utility load confirmation required"],
    risks: ["Industrial buyer pool is diligence-heavy.", "Utility capacity must be documented.", "Large ticket size narrows liquidity."],
  }),
  makeActiveProperty({
    id: "guiones-villas-development-land",
    title: "Guiones Villas Development Land",
    province: "Guanacaste",
    canton: "Nicoya",
    district: "Nosara",
    address: "Playa Guiones access area, low-density villa development setting",
    coordinates: { lat: 9.9458, lng: -85.6631 },
    propertyType: "Tourism development land",
    landSize: 2400,
    ownerPrice: 1668000,
    landUse: "Tourism residential",
    servicesAvailable: "Electricity nearby, road access, water source to validate",
    roadAccess: "Gravel public road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 73,
    liquidityScore: 66,
    riskScore: 45,
    zoningFit: 71,
    infrastructureScore: 62,
    brokerAssigned: "marco-hidalgo",
    brokerName: "Marco Hidalgo",
    scoreExplanation: "Premium Guiones demand supports villa development if water and buildable envelope are confirmed.",
    ownerAlignment: "Owner price reflects premium district expectations and needs strong documentation.",
    parcel: { registryId: "GU-NIC-99014", frontage: "40 m", depth: "60 m", coverage: "Low-density tourism" },
    nearbyServices: [
      { name: "Playa Guiones", category: "Infrastructure", distance: "1.5 km", note: "Premium beach demand" },
      { name: "Wellness cluster", category: "Retail", distance: "1.2 km", note: "Tourism amenities" },
      { name: "Nosara airport", category: "Transit", distance: "8.0 km", note: "Regional access" },
      { name: "Restaurants", category: "Retail", distance: "1.1 km", note: "Visitor services" },
    ],
    analystNote: "High-demand coastal development site. Water and environmental constraints drive risk.",
    zoningClassification: "Low-Density Tourism Residential",
    permitted: ["Villas", "Small lodging", "Wellness amenities"],
    restrictions: ["Water proof required", "Environmental review", "Density limits"],
    risks: ["Water is unresolved.", "Premium price increases downside risk.", "Road conditions may affect construction."],
  }),
  makeActiveProperty({
    id: "herradura-hospitality-land",
    title: "Herradura Hospitality Land",
    province: "Puntarenas",
    canton: "Garabito",
    district: "Herradura",
    address: "Herradura hospitality corridor, near marina access",
    coordinates: { lat: 9.6501, lng: -84.6574 },
    propertyType: "Hospitality land",
    landSize: 3400,
    ownerPrice: 1547000,
    landUse: "Tourism lodging",
    servicesAvailable: "Water nearby, electricity nearby, paved access, marina tourism demand",
    roadAccess: "Paved public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 77,
    liquidityScore: 70,
    riskScore: 39,
    zoningFit: 75,
    infrastructureScore: 76,
    brokerAssigned: "sofia-quesada",
    brokerName: "Sofia Quesada",
    scoreExplanation: "Marina-adjacent tourism demand supports hospitality or villa development positioning.",
    ownerAlignment: "Owner price is within coastal hospitality support if access and water are confirmed.",
    parcel: { registryId: "PU-GAR-55077", frontage: "52 m", depth: "65 m", coverage: "Tourism review required" },
    nearbyServices: [
      { name: "Los Suenos marina", category: "Infrastructure", distance: "3.8 km", note: "Premium tourism node" },
      { name: "Route 34", category: "Transit", distance: "1.0 km", note: "Coastal highway" },
      { name: "Herradura beach", category: "Infrastructure", distance: "2.5 km", note: "Tourism demand" },
      { name: "Jaco center", category: "Retail", distance: "8.8 km", note: "Visitor services" },
    ],
    analystNote: "Good coastal hospitality candidate. Use marina and Jaco comps rather than raw land references.",
    zoningClassification: "Tourism Commercial",
    permitted: ["Lodging", "Villas", "Restaurants", "Wellness services"],
    restrictions: ["Environmental review", "Setbacks to waterways", "Traffic access review"],
    risks: ["Coastal construction costs are elevated.", "Water service must be confirmed.", "Seasonality affects revenue assumptions."],
  }),
  makeActiveProperty({
    id: "sabanilla-infill-parcel",
    title: "Sabanilla Infill Parcel",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "Sabanilla",
    address: "Sabanilla, near university services and residential demand",
    coordinates: { lat: 9.9362, lng: -84.0369 },
    propertyType: "Urban lot",
    landSize: 940,
    ownerPrice: 512000,
    landUse: "Urban residential",
    servicesAvailable: "Water, electricity, public transport, neighborhood services",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 70,
    liquidityScore: 76,
    riskScore: 34,
    zoningFit: 70,
    infrastructureScore: 78,
    brokerAssigned: "natalia-leiva",
    brokerName: "Natalia Leiva",
    scoreExplanation: "Compact urban lot with reliable services and student-adjacent residential demand.",
    ownerAlignment: "Owner price is fair if zoning supports small multifamily redevelopment.",
    parcel: { registryId: "SJ-MOC-34180", frontage: "22 m", depth: "43 m", coverage: "Medium-density urban" },
    nearbyServices: [
      { name: "University services", category: "Education", distance: "1.8 km", note: "Rental demand" },
      { name: "Sabanilla center", category: "Retail", distance: "0.6 km", note: "Neighborhood services" },
      { name: "Bus corridor", category: "Transit", distance: "0.2 km", note: "Public transport" },
      { name: "Curridabat access", category: "Transit", distance: "2.6 km", note: "East-side mobility" },
    ],
    analystNote: "Smaller infill play. Good for conservative rental housing or owner-user redevelopment.",
    zoningClassification: "Urban Residential",
    permitted: ["Single-family housing", "Small multifamily", "Professional services"],
    restrictions: ["Parking minimums", "Height limits", "Setbacks to confirm"],
    risks: ["Small lot limits design flexibility.", "Parking can constrain density.", "Upside depends on zoning interpretation."],
  }),
  makeActiveProperty({
    id: "samara-ridge-retreat-land",
    title: "Samara Ridge Retreat Land",
    province: "Guanacaste",
    canton: "Nicoya",
    district: "Samara",
    address: "Samara ridge, eco-retreat setting with ocean-view potential",
    coordinates: { lat: 9.8822, lng: -85.5287 },
    propertyType: "Mountain eco-lot",
    landSize: 7400,
    ownerPrice: 2109000,
    landUse: "Eco-retreat",
    servicesAvailable: "Electricity nearby, water source to validate, gravel access",
    roadAccess: "Gravel public road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 68,
    liquidityScore: 60,
    riskScore: 48,
    zoningFit: 69,
    infrastructureScore: 58,
    brokerAssigned: "marco-hidalgo",
    brokerName: "Marco Hidalgo",
    scoreExplanation: "Lifestyle and retreat demand exist, but infrastructure uncertainty keeps risk elevated.",
    ownerAlignment: "Owner price needs clear water, road, and buildability evidence.",
    parcel: { registryId: "GU-NIC-76031", frontage: "110 m", depth: "67 m", coverage: "Eco-retreat review" },
    nearbyServices: [
      { name: "Samara beach", category: "Infrastructure", distance: "5.5 km", note: "Tourism demand" },
      { name: "Nicoya services", category: "Infrastructure", distance: "31 km", note: "Regional services" },
      { name: "Local restaurants", category: "Retail", distance: "5.0 km", note: "Visitor amenities" },
      { name: "Coastal road", category: "Transit", distance: "3.2 km", note: "Regional access" },
    ],
    analystNote: "Beautiful but diligence-heavy. Good demo case for elevated risk with tourism upside.",
    zoningClassification: "Eco-Residential Tourism",
    permitted: ["Eco-retreat", "Low-density villas", "Wellness use"],
    restrictions: ["Water proof required", "Slope review", "Environmental review"],
    risks: ["Water source uncertain.", "Road access can be seasonal.", "Large parcel may have limited buildable area."],
  }),
  makeActiveProperty({
    id: "cariari-service-parcel",
    title: "Cariari Service Parcel",
    province: "Heredia",
    canton: "Belen",
    district: "Asuncion",
    address: "Cariari service corridor near hotels, offices, and airport access",
    coordinates: { lat: 9.9796, lng: -84.1544 },
    propertyType: "Commercial corner",
    landSize: 1520,
    ownerPrice: 973000,
    landUse: "Hotel and office support services",
    servicesAvailable: "Water, electricity, fiber, airport access, hotel and office services",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 78,
    liquidityScore: 77,
    riskScore: 31,
    zoningFit: 79,
    infrastructureScore: 85,
    brokerAssigned: "isabel-nunez",
    brokerName: "Isabel Nunez",
    scoreExplanation: "Business hotel and airport demand support service retail or office support uses.",
    ownerAlignment: "Owner price is aligned with comparable service-commercial sites.",
    parcel: { registryId: "HE-BEL-66230", frontage: "36 m", depth: "42 m", coverage: "65% max coverage" },
    nearbyServices: [
      { name: "Cariari office cluster", category: "Infrastructure", distance: "0.8 km", note: "Office demand" },
      { name: "Business hotels", category: "Retail", distance: "0.5 km", note: "Visitor services" },
      { name: "Route 1", category: "Transit", distance: "1.5 km", note: "Regional access" },
      { name: "SJO Airport", category: "Transit", distance: "6.0 km", note: "Airport demand" },
    ],
    analystNote: "Practical service-commercial site with a clear corporate and airport demand story.",
    zoningClassification: "Commercial Services",
    permitted: ["Retail services", "Offices", "Restaurants", "Medical services"],
    restrictions: ["Parking ratio applies", "Traffic access review", "Setbacks to confirm"],
    risks: ["Access and parking drive final value.", "Corporate demand can be cyclical.", "Small site limits large-format users."],
  }),
  makeActiveProperty({
    id: "paraiso-urban-services-lot",
    title: "Paraiso Urban Services Lot",
    province: "Cartago",
    canton: "Paraiso",
    district: "Paraiso",
    address: "Paraiso center, urban services corridor",
    coordinates: { lat: 9.8388, lng: -83.8668 },
    propertyType: "Urban lot",
    landSize: 950,
    ownerPrice: 214000,
    landUse: "Urban services",
    servicesAvailable: "Water, electricity, public road, town services",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 61,
    liquidityScore: 64,
    riskScore: 36,
    zoningFit: 68,
    infrastructureScore: 70,
    brokerAssigned: "valeria-castro",
    brokerName: "Valeria Castro",
    scoreExplanation: "Affordable regional urban lot with basic services and modest upside.",
    ownerAlignment: "Owner price appears market-aligned for a smaller regional town lot.",
    parcel: { registryId: "CA-PAR-19004", frontage: "25 m", depth: "38 m", coverage: "Urban services" },
    nearbyServices: [
      { name: "Paraiso center", category: "Retail", distance: "0.4 km", note: "Town services" },
      { name: "Bus routes", category: "Transit", distance: "0.2 km", note: "Mobility" },
      { name: "Schools", category: "Education", distance: "0.8 km", note: "Local demand" },
      { name: "Cartago center", category: "Infrastructure", distance: "9.5 km", note: "Regional services" },
    ],
    analystNote: "Lower-ticket regional asset. Best for local owner-users or small service operators.",
    zoningClassification: "Urban Services",
    permitted: ["Residential", "Small retail", "Professional services"],
    restrictions: ["Height limits", "Setbacks to confirm", "Parking minimums"],
    risks: ["Liquidity is local-market dependent.", "Upside is modest.", "Comparable evidence may be thin."],
  }),
  makeActiveProperty({
    id: "la-guacima-residential-land",
    title: "La Guacima Residential Development Land",
    province: "Alajuela",
    canton: "Alajuela",
    district: "La Guacima",
    address: "La Guacima, west of airport corridor near residential communities",
    coordinates: { lat: 9.9647, lng: -84.2591 },
    propertyType: "Residential development land",
    landSize: 4800,
    ownerPrice: 1176000,
    landUse: "Residential development",
    servicesAvailable: "Water nearby, electricity nearby, paved road, residential demand",
    roadAccess: "Paved public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 69,
    liquidityScore: 66,
    riskScore: 39,
    zoningFit: 72,
    infrastructureScore: 70,
    brokerAssigned: "oscar-benavides",
    brokerName: "Oscar Benavides",
    scoreExplanation: "West Alajuela residential growth supports a moderate-risk development land story.",
    ownerAlignment: "Owner price is plausible if water and road frontage support subdivision.",
    parcel: { registryId: "AL-ALJ-22176", frontage: "75 m", depth: "64 m", coverage: "Residential expansion" },
    nearbyServices: [
      { name: "La Guacima center", category: "Retail", distance: "2.1 km", note: "Local services" },
      { name: "Route 27 access", category: "Transit", distance: "6.8 km", note: "Regional access" },
      { name: "Residential communities", category: "Infrastructure", distance: "1.2 km", note: "Demand signal" },
      { name: "Airport corridor", category: "Transit", distance: "11 km", note: "Employment access" },
    ],
    analystNote: "Good residential expansion candidate, but subdivision feasibility should be verified.",
    zoningClassification: "Residential Expansion",
    permitted: ["Residential subdivision", "Single-family homes", "Community amenities"],
    restrictions: ["Water letter required", "Subdivision approvals", "Road improvement may apply"],
    risks: ["Water timing can affect development.", "Absorption is slower than central GAM.", "Subdivision approvals add timeline risk."],
  }),
  makeActiveProperty({
    id: "barrio-escalante-commercial-corner",
    title: "Barrio Escalante Commercial Corner",
    province: "San Jose",
    canton: "San Jose",
    district: "Carmen",
    address: "Barrio Escalante restaurant and services corridor",
    coordinates: { lat: 9.9367, lng: -84.0615 },
    propertyType: "Commercial corner",
    landSize: 620,
    ownerPrice: 583000,
    landUse: "Restaurant and services",
    servicesAvailable: "Water, electricity, sewer, fiber, high foot traffic",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 74,
    liquidityScore: 78,
    riskScore: 33,
    zoningFit: 71,
    infrastructureScore: 88,
    brokerAssigned: "natalia-leiva",
    brokerName: "Natalia Leiva",
    scoreExplanation: "Small but high-visibility commercial corner in a strong lifestyle district.",
    ownerAlignment: "Owner price is premium but consistent with walkable commercial demand.",
    parcel: { registryId: "SJ-CAR-88041", frontage: "20 m", depth: "31 m", coverage: "Urban commercial" },
    nearbyServices: [
      { name: "Restaurant corridor", category: "Retail", distance: "0.1 km", note: "Foot traffic" },
      { name: "San Jose center", category: "Infrastructure", distance: "1.5 km", note: "Urban services" },
      { name: "University district", category: "Education", distance: "1.6 km", note: "Demand driver" },
      { name: "Bus routes", category: "Transit", distance: "0.2 km", note: "Urban mobility" },
    ],
    analystNote: "Good small-ticket urban commercial asset. Useful for food, services, or boutique office concepts.",
    zoningClassification: "Urban Commercial",
    permitted: ["Restaurants", "Retail", "Offices", "Professional services"],
    restrictions: ["Noise controls", "Parking limitations", "Heritage district review may apply"],
    risks: ["Small lot limits redevelopment.", "Parking availability is constrained.", "Premium per-meter pricing requires owner-user demand."],
  }),
  makeActiveProperty({
    id: "naranjo-view-residential-land",
    title: "Naranjo View Residential Land",
    province: "Alajuela",
    canton: "Naranjo",
    district: "Naranjo",
    address: "Naranjo hillside residential expansion area",
    coordinates: { lat: 10.0986, lng: -84.3867 },
    propertyType: "Mountain eco-lot",
    landSize: 6900,
    ownerPrice: 780000,
    landUse: "Residential lifestyle",
    servicesAvailable: "Electricity nearby, water to confirm, public road frontage",
    roadAccess: "Paved public road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 63,
    liquidityScore: 56,
    riskScore: 44,
    zoningFit: 66,
    infrastructureScore: 60,
    brokerAssigned: "ricardo-sanchez",
    brokerName: "Ricardo Sanchez",
    scoreExplanation: "Affordable mountain-view land with lifestyle appeal, but liquidity and water proof are key constraints.",
    ownerAlignment: "Owner price is reasonable if water can be documented.",
    parcel: { registryId: "AL-NAR-50114", frontage: "95 m", depth: "72 m", coverage: "Low-density residential" },
    nearbyServices: [
      { name: "Naranjo center", category: "Retail", distance: "3.4 km", note: "Town services" },
      { name: "Route 1 access", category: "Transit", distance: "8.5 km", note: "Regional access" },
      { name: "View corridor", category: "Infrastructure", distance: "On-site", note: "Lifestyle premium" },
      { name: "Schools", category: "Education", distance: "4.0 km", note: "Family demand" },
    ],
    analystNote: "Good lifestyle land for patient buyers. Water and slope information should be gathered first.",
    zoningClassification: "Low-Density Residential",
    permitted: ["Single-family homes", "Eco-residential", "Small farm use"],
    restrictions: ["Water proof required", "Slope review", "Subdivision approvals if divided"],
    risks: ["Liquidity is slower outside core towns.", "Water proof is unresolved.", "Slope can reduce buildable area."],
  }),
  makeActiveProperty({
    id: "playa-grande-hospitality-edge",
    title: "Playa Grande Hospitality Edge",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Cabo Velas",
    address: "Playa Grande edge, tourism and villa corridor",
    coordinates: { lat: 10.3334, lng: -85.8421 },
    propertyType: "Tourism development land",
    landSize: 4200,
    ownerPrice: 1953000,
    landUse: "Tourism and villas",
    servicesAvailable: "Electricity nearby, water to validate, tourism road access",
    roadAccess: "Gravel public road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 71,
    liquidityScore: 64,
    riskScore: 47,
    zoningFit: 70,
    infrastructureScore: 61,
    brokerAssigned: "carlos-rojas",
    brokerName: "Carlos Rojas",
    scoreExplanation: "Tourism upside near Playa Grande is strong, but infrastructure and environmental review are material.",
    ownerAlignment: "Owner price needs strong development feasibility evidence.",
    parcel: { registryId: "GU-SCZ-66491", frontage: "68 m", depth: "62 m", coverage: "Tourism low-density" },
    nearbyServices: [
      { name: "Playa Grande", category: "Infrastructure", distance: "2.0 km", note: "Tourism anchor" },
      { name: "Tamarindo", category: "Retail", distance: "8.5 km", note: "Visitor services" },
      { name: "Route 152", category: "Transit", distance: "5.2 km", note: "Regional access" },
      { name: "Marine park edge", category: "Infrastructure", distance: "Nearby", note: "Environmental sensitivity" },
    ],
    analystNote: "Tourism buyer interest is likely, but diligence should be conservative around water and protected-area constraints.",
    zoningClassification: "Tourism Low Density",
    permitted: ["Villas", "Small lodging", "Wellness amenities"],
    restrictions: ["Environmental review", "Density limits", "Water proof required"],
    risks: ["Environmental restrictions may affect design.", "Water is unresolved.", "Road quality may affect visitor experience."],
  }),
  makeActiveProperty({
    id: "rio-segundo-warehouse-land",
    title: "Rio Segundo Warehouse Land",
    province: "Alajuela",
    canton: "Alajuela",
    district: "Rio Segundo",
    address: "Rio Segundo, warehouse corridor near airport access",
    coordinates: { lat: 10.0008, lng: -84.2034 },
    propertyType: "Industrial lot",
    landSize: 3800,
    ownerPrice: 1748000,
    landUse: "Warehousing and airport services",
    servicesAvailable: "Water nearby, electricity nearby, truck access, airport logistics demand",
    roadAccess: "Paved public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 81,
    liquidityScore: 78,
    riskScore: 30,
    zoningFit: 82,
    infrastructureScore: 88,
    brokerAssigned: "oscar-benavides",
    brokerName: "Oscar Benavides",
    scoreExplanation: "Airport-adjacent warehouse land with practical size and strong access fundamentals.",
    ownerAlignment: "Owner price is supportable if industrial use and utility capacity are confirmed.",
    parcel: { registryId: "AL-ALJ-49028", frontage: "55 m", depth: "69 m", coverage: "65% max coverage" },
    nearbyServices: [
      { name: "SJO Airport", category: "Transit", distance: "2.8 km", note: "Logistics demand" },
      { name: "Route 1", category: "Transit", distance: "0.9 km", note: "Regional access" },
      { name: "Warehouse cluster", category: "Infrastructure", distance: "0.7 km", note: "Industrial demand" },
      { name: "Airport hotels", category: "Retail", distance: "2.0 km", note: "Service demand" },
    ],
    analystNote: "Strong airport industrial candidate with manageable lot size.",
    zoningClassification: "Industrial Services",
    permitted: ["Warehousing", "Distribution", "Industrial services"],
    restrictions: ["Traffic access review", "Utility load confirmation", "Environmental compliance"],
    risks: ["Industrial use must be documented.", "Truck access design matters.", "Utility capacity may affect buyer underwriting."],
  }),
  makeActiveProperty({
    id: "el-guarco-expansion-land",
    title: "El Guarco Expansion Land",
    province: "Cartago",
    canton: "El Guarco",
    district: "Tejar",
    address: "Tejar de El Guarco, suburban residential expansion area",
    coordinates: { lat: 9.8444, lng: -83.9383 },
    propertyType: "Residential development land",
    landSize: 6100,
    ownerPrice: 1128000,
    landUse: "Residential expansion",
    servicesAvailable: "Water nearby, electricity nearby, paved road, schools nearby",
    roadAccess: "Paved public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    investmentScore: 67,
    liquidityScore: 62,
    riskScore: 40,
    zoningFit: 72,
    infrastructureScore: 68,
    brokerAssigned: "valeria-castro",
    brokerName: "Valeria Castro",
    scoreExplanation: "Residential growth corridor with reasonable entry price and practical services.",
    ownerAlignment: "Owner price is market-aligned if subdivision and utility timing are clear.",
    parcel: { registryId: "CA-EGU-11830", frontage: "86 m", depth: "71 m", coverage: "Residential expansion" },
    nearbyServices: [
      { name: "Tejar center", category: "Retail", distance: "1.8 km", note: "Town services" },
      { name: "Route 2", category: "Transit", distance: "1.1 km", note: "Regional access" },
      { name: "Schools", category: "Education", distance: "1.2 km", note: "Family demand" },
      { name: "Cartago center", category: "Infrastructure", distance: "5.8 km", note: "Regional services" },
    ],
    analystNote: "Good suburban residential land if utilities and subdivision path are confirmed.",
    zoningClassification: "Residential Expansion",
    permitted: ["Residential subdivision", "Single-family homes", "Community amenities"],
    restrictions: ["Subdivision approvals", "Water letter required", "Road improvements may apply"],
    risks: ["Absorption may be gradual.", "Utility timing affects feasibility.", "Subdivision approvals add timeline risk."],
  }),
  makeActiveProperty({
    id: "los-yoses-redevelopment-site",
    title: "Los Yoses Redevelopment Site",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "San Pedro",
    address: "Los Yoses, near cultural, university, and service corridors",
    coordinates: { lat: 9.9307, lng: -84.0643 },
    propertyType: "Mixed-use parcel",
    landSize: 1120,
    ownerPrice: 913000,
    landUse: "Mixed-use redevelopment",
    servicesAvailable: "Water, electricity, sewer, fiber, public transport",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 78,
    liquidityScore: 80,
    riskScore: 30,
    zoningFit: 76,
    infrastructureScore: 89,
    brokerAssigned: "natalia-leiva",
    brokerName: "Natalia Leiva",
    scoreExplanation: "Central east-side redevelopment site with strong services, rental, and lifestyle demand.",
    ownerAlignment: "Owner price is premium but supported by location if density is confirmed.",
    parcel: { registryId: "SJ-MOC-88022", frontage: "30 m", depth: "37 m", coverage: "Mixed-use urban" },
    nearbyServices: [
      { name: "Los Yoses services", category: "Retail", distance: "0.2 km", note: "Lifestyle demand" },
      { name: "University corridor", category: "Education", distance: "1.2 km", note: "Rental demand" },
      { name: "Barrio Escalante", category: "Retail", distance: "1.0 km", note: "Food and culture" },
      { name: "Public transport", category: "Transit", distance: "0.3 km", note: "Urban mobility" },
    ],
    analystNote: "Strong infill parcel with multiple use cases. Parking and density drive the final valuation.",
    zoningClassification: "Mixed Urban Redevelopment",
    permitted: ["Apartments", "Offices", "Retail services", "Professional services"],
    restrictions: ["Parking minimums", "Height review", "Setbacks to confirm"],
    risks: ["Parking can limit development intensity.", "Premium price narrows investor margin.", "Neighborhood sensitivity may affect design."],
  }),
  makeActiveProperty({
    id: "palmares-urban-lot",
    title: "Palmares Urban Lot",
    province: "Alajuela",
    canton: "Palmares",
    district: "Palmares",
    address: "Palmares center, near regional services and public road frontage",
    coordinates: { lat: 10.0562, lng: -84.4315 },
    propertyType: "Urban lot",
    landSize: 1280,
    ownerPrice: 326000,
    landUse: "Urban residential and services",
    servicesAvailable: "Water, electricity, public road, town services",
    roadAccess: "Paved public road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    investmentScore: 62,
    liquidityScore: 60,
    riskScore: 35,
    zoningFit: 67,
    infrastructureScore: 69,
    brokerAssigned: "ricardo-sanchez",
    brokerName: "Ricardo Sanchez",
    scoreExplanation: "Affordable regional urban lot with practical owner-user and small developer demand.",
    ownerAlignment: "Owner price is reasonable for a serviced regional town parcel.",
    parcel: { registryId: "AL-PAL-34077", frontage: "31 m", depth: "41 m", coverage: "Urban residential" },
    nearbyServices: [
      { name: "Palmares center", category: "Retail", distance: "0.6 km", note: "Town services" },
      { name: "Route 1 access", category: "Transit", distance: "6.2 km", note: "Regional mobility" },
      { name: "Schools", category: "Education", distance: "0.9 km", note: "Family demand" },
      { name: "Medical clinic", category: "Health", distance: "1.1 km", note: "Basic services" },
    ],
    analystNote: "Modest but clean regional asset. Good for local buyer demonstrations in the dashboard.",
    zoningClassification: "Urban Residential Services",
    permitted: ["Residential", "Small retail", "Professional services"],
    restrictions: ["Parking requirements", "Setbacks to confirm", "Height limits"],
    risks: ["Liquidity is local-market dependent.", "Upside is limited.", "Comparable evidence may be less frequent."],
  }),
  makeActiveProperty({
    id: "ruta21-logistics-parcel",
    title: "Ruta 21 Logistics Parcel",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Liberia",
    address: "Ruta 21 logistics corridor, outside Liberia center",
    coordinates: { lat: 10.6157, lng: -85.4524 },
    propertyType: "Logistics parcel",
    landSize: 7800,
    ownerPrice: 1365000,
    landUse: "Logistics and storage",
    servicesAvailable: "Electricity nearby, water to confirm, heavy vehicle road access",
    roadAccess: "Paved public road",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    investmentScore: 70,
    liquidityScore: 63,
    riskScore: 42,
    zoningFit: 74,
    infrastructureScore: 70,
    brokerAssigned: "andres-solis",
    brokerName: "Andres Solis",
    scoreExplanation: "Large regional logistics parcel with good road access but thinner buyer liquidity than GAM industrial nodes.",
    ownerAlignment: "Owner price is reasonable but water and zoning evidence will drive confidence.",
    parcel: { registryId: "GU-LIB-88231", frontage: "112 m", depth: "70 m", coverage: "Industrial services review" },
    nearbyServices: [
      { name: "Ruta 21", category: "Transit", distance: "0.2 km", note: "Regional logistics" },
      { name: "Liberia center", category: "Retail", distance: "5.0 km", note: "Labor and services" },
      { name: "Airport", category: "Transit", distance: "15 km", note: "Air access" },
      { name: "Industrial services", category: "Infrastructure", distance: "2.8 km", note: "Support uses" },
    ],
    analystNote: "Useful regional logistics demo case. Less premium than airport corridor but practical for storage and service uses.",
    zoningClassification: "Regional Logistics",
    permitted: ["Storage", "Distribution", "Industrial services", "Vehicle services"],
    restrictions: ["Water proof required", "Traffic access review", "Environmental compliance"],
    risks: ["Buyer pool is narrower.", "Water is unresolved.", "Regional pricing is more volatile."],
  }),
];

export const initialProperties = [...coreProperties, ...additionalProperties];

export function formatCurrency(value) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(Number(value) || 0);
}

export function formatNumber(value) {
  return new Intl.NumberFormat("en-US").format(Number(value) || 0);
}

export function getUniqueOptions(properties, key) {
  return [...new Set(properties.map((property) => property[key]).filter(Boolean))].sort();
}

export function haversineKm(a, b) {
  const radius = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;

  return radius * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

function typeFamily(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/development/g, "")
    .replace(/land/g, "")
    .replace(/parcel/g, "")
    .trim();
}

function comparableScore(target, comparable, distanceKm) {
  let score = Number(comparable.similarityScore) || 45;

  if (target.province === comparable.province) score += 10;
  if (target.canton === comparable.canton) score += 12;
  if (target.district === comparable.district) score += 6;
  if (typeFamily(target.propertyType) === typeFamily(comparable.propertyType)) score += 10;

  const targetLandSize = Number(target.landSize) || 1;
  const comparableLandSize = Number(comparable.landSize) || 1;
  const areaRatio =
    Math.min(targetLandSize, comparableLandSize) /
    Math.max(targetLandSize, comparableLandSize);

  score += Math.round(areaRatio * 8);
  score -= Math.min(18, Math.round(distanceKm / 8));

  return Math.max(25, Math.min(score, 99));
}

export function getComparables(target) {
  if (!target?.coordinates?.lat || !target?.coordinates?.lng) return [];

  return comparableProperties
    .map((comparable) => {
      const distanceKm = Number(haversineKm(target.coordinates, comparable.coordinates).toFixed(1));

      return {
        ...comparable,
        distanceKm,
        distanceFromSelected: distanceKm,
        similarityScore: comparableScore(target, comparable, distanceKm),
      };
    })
    .sort((a, b) => b.similarityScore - a.similarityScore || a.distanceKm - b.distanceKm)
    .slice(0, 6);
}

export function makePropertyFromForm(form) {
  const ownerPrice = Number(form.ownerPrice) || 0;
  const landSize = Number(form.landSize) || 1;
  const pricePerM2 = Number(form.pricePerM2) || Math.round(ownerPrice / landSize);
  const name = form.name.trim() || "New Property";
  const idBase = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const marketPrice = Math.round(pricePerM2 * landSize * 1.04);
  const riskScore = 42;

  return {
    id: `${idBase || "property"}-${Date.now()}`,
    name,
    title: name,
    province: form.province.trim() || "San Jose",
    canton: form.canton.trim() || "Central",
    district: form.district.trim() || "Pending district",
    address: form.address.trim() || "Address pending",
    latitude: Number(form.lat) || 9.9281,
    longitude: Number(form.lng) || -84.0907,
    coordinates: {
      lat: Number(form.lat) || 9.9281,
      lng: Number(form.lng) || -84.0907,
    },
    ownerPrice,
    marketPrice,
    appraisalPrice: Math.round(ownerPrice * 0.86),
    landSize,
    landSizeM2: landSize,
    landUse: form.landUse.trim() || "Pending classification",
    propertyType: form.propertyType || "Urban lot",
    pricePerM2,
    servicesAvailable: "Pending broker validation",
    roadAccess: "Pending broker validation",
    waterAvailability: "Needs validation",
    electricityAvailability: "Needs validation",
    brokerAssigned: "maria-alfaro",
    investmentScore: 67,
    liquidityScore: 65,
    infrastructureScore: 62,
    zoningScore: 61,
    zoningFit: 61,
    riskScore,
    tags: makeTags(form.province || "Costa Rica", form.canton || "New intake", form.propertyType || "Property"),
    scoreExplanation:
      "New intake property. Complete site visit notes, zoning review, and comparables to improve the investment score.",
    ownerAlignment:
      "Market support is provisional until additional comparable evidence is added.",
    nearbyServices: [
      { name: "Access route review", category: "Transit", distance: "Pending", note: "Broker to confirm after visit" },
      { name: "Municipal zoning office", category: "Infrastructure", distance: "Pending", note: "Required for use validation" },
    ],
    notes: form.notes.trim()
      ? [{ author: "Broker", date: currentNoteDate(), text: form.notes.trim() }]
      : [],
    photos: ["Satellite view", "Street frontage", "Parcel access"],
    parcelPlan: "Pending parcel plan",
    parcel: {
      registryId: "Pending registry",
      frontage: "Pending",
      depth: "Pending",
      coverage: "Pending municipal validation",
    },
    zoning: {
      classification: "Pending classification",
      permitted: ["To be confirmed with municipality"],
      restrictions: ["Confirm setbacks, coverage, and permitted use"],
    },
    risks: [
      "Zoning and registry records need validation.",
      "Comparable support is provisional until the property is reviewed.",
      "Infrastructure availability should be checked before investor presentation.",
    ],
  };
}

export function currentNoteDate() {
  return new Date().toLocaleDateString("en-US", { month: "short", year: "numeric" });
}
