function photoPlaceholder(label, color = "#0f9488") {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="320" height="220" viewBox="0 0 320 220"><rect width="320" height="220" fill="#f5f1eb"/><rect x="18" y="18" width="284" height="184" rx="14" fill="${color}" opacity="0.14"/><circle cx="160" cy="92" r="28" fill="${color}" opacity="0.28"/><text x="160" y="145" text-anchor="middle" font-family="Arial" font-size="18" font-weight="700" fill="#1f2a3d">${label}</text></svg>`;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

function makeRequest({
  id,
  status,
  submittedAt,
  ownerName,
  email,
  phone,
  title,
  province,
  canton,
  district,
  exactAddress,
  propertyType,
  landSizeM2,
  ownerAskingPrice,
  estimatedPricePerM2,
  landUse,
  servicesAvailable,
  waterAvailability,
  electricityAvailability,
  roadAccess,
  preferredBrokerId,
  notes,
}) {
  return {
    id,
    status,
    submittedAt,
    owner: {
      fullName: ownerName,
      email,
      phone,
    },
    property: {
      title,
      province,
      canton,
      district,
      exactAddress,
      propertyType,
      landSizeM2,
      ownerAskingPrice,
      estimatedPricePerM2,
      landUse,
      servicesAvailable,
      waterAvailability,
      electricityAvailability,
      roadAccess,
      notes,
    },
    preferredBrokerId,
    parcelPlan: {
      name: `${id}-parcel-plan.pdf`,
      type: "application/pdf",
      size: 1240000,
    },
    photos: [
      { name: `${id}-frontage.webp`, type: "image/webp", size: 284000, dataUrl: photoPlaceholder("Frontage") },
      { name: `${id}-access.webp`, type: "image/webp", size: 312000, dataUrl: photoPlaceholder("Access", "#df6a3c") },
      { name: `${id}-context.webp`, type: "image/webp", size: 298000, dataUrl: photoPlaceholder("Context", "#344155") },
    ],
  };
}

export const seededPropertyRequests = [
  makeRequest({
    id: "request-escazu-guachipelin-office-edge",
    status: "New",
    submittedAt: "2026-05-20T15:20:00.000Z",
    ownerName: "Roberto Vargas",
    email: "roberto.vargas@example.com",
    phone: "+506 8821 1904",
    title: "Guachipelin Office Edge Lot",
    province: "San Jose",
    canton: "Escazu",
    district: "Guachipelin",
    exactAddress: "Guachipelin de Escazu, 600 m west of the corporate park entrance",
    propertyType: "commercial corner",
    landSizeM2: "1680",
    ownerAskingPrice: "1580000",
    estimatedPricePerM2: "940",
    landUse: "Office and services",
    servicesAvailable: "Water, electricity, fiber internet, paved road frontage",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "monica-salas",
    notes: "Owner wants a broker opinion before launching publicly.",
  }),
  makeRequest({
    id: "request-santa-ana-pozos-flex",
    status: "In Review",
    submittedAt: "2026-05-19T18:45:00.000Z",
    ownerName: "Fernanda Soto",
    email: "fernanda.soto@example.com",
    phone: "+506 8712 4408",
    title: "Pozos Flex Warehouse Parcel",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Pozos",
    exactAddress: "Pozos, near Ruta 27 service access and Lindora business corridor",
    propertyType: "logistics parcel",
    landSizeM2: "5100",
    ownerAskingPrice: "2650000",
    estimatedPricePerM2: "520",
    landUse: "Light industrial and services",
    servicesAvailable: "Water, three-phase electricity nearby, truck access",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    roadAccess: "Paved public road",
    preferredBrokerId: "diego-vargas",
    notes: "Truck turning radius and utility capacity need validation.",
  }),
  makeRequest({
    id: "request-heredia-mercedes-residential",
    status: "Approved",
    submittedAt: "2026-05-18T13:10:00.000Z",
    ownerName: "Lucia Araya",
    email: "lucia.araya@example.com",
    phone: "+506 7202 6041",
    title: "Mercedes Student Residence Site",
    province: "Heredia",
    canton: "Heredia",
    district: "Mercedes",
    exactAddress: "Mercedes, walking distance to Universidad Nacional",
    propertyType: "residential development land",
    landSizeM2: "940",
    ownerAskingPrice: "585000",
    estimatedPricePerM2: "622",
    landUse: "Medium-density residential",
    servicesAvailable: "Water, electricity, public transport nearby",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "ana-campos",
    notes: "Good candidate for student housing if parking can be resolved.",
  }),
  makeRequest({
    id: "request-tamarindo-beach-corridor",
    status: "Needs Info",
    submittedAt: "2026-05-17T20:35:00.000Z",
    ownerName: "Michael Brenes",
    email: "michael.brenes@example.com",
    phone: "+506 8894 2270",
    title: "Tamarindo Beach Corridor Parcel",
    province: "Guanacaste",
    canton: "Santa Cruz",
    district: "Tamarindo",
    exactAddress: "Tamarindo beach corridor, 900 m from beach access",
    propertyType: "hospitality land",
    landSizeM2: "2600",
    ownerAskingPrice: "1540000",
    estimatedPricePerM2: "592",
    landUse: "Tourism commercial",
    servicesAvailable: "Electricity, road access, water availability pending",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    roadAccess: "Paved public road",
    preferredBrokerId: "carlos-rojas",
    notes: "Please confirm water letter and maritime setback exposure.",
  }),
  makeRequest({
    id: "request-liberia-airport-service",
    status: "New",
    submittedAt: "2026-05-16T16:05:00.000Z",
    ownerName: "Adriana Calvo",
    email: "adriana.calvo@example.com",
    phone: "+506 6049 8830",
    title: "Liberia Airport Service Lot",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Liberia",
    exactAddress: "Route to Daniel Oduber airport, near rental car services",
    propertyType: "commercial corner",
    landSizeM2: "3700",
    ownerAskingPrice: "1110000",
    estimatedPricePerM2: "300",
    landUse: "Airport services",
    servicesAvailable: "Water, electricity, paved frontage",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    roadAccess: "Paved public road",
    preferredBrokerId: "andres-solis",
    notes: "Owner wants regional commercial buyer exposure.",
  }),
  makeRequest({
    id: "request-jaco-beachfront",
    status: "In Review",
    submittedAt: "2026-05-15T12:50:00.000Z",
    ownerName: "Carolina Ulate",
    email: "carolina.ulate@example.com",
    phone: "+506 8342 9075",
    title: "Jaco Beachfront Opportunity",
    province: "Puntarenas",
    canton: "Garabito",
    district: "Jaco",
    exactAddress: "Central Jaco beachfront, near hotel and restaurant zone",
    propertyType: "beachfront opportunity",
    landSizeM2: "1750",
    ownerAskingPrice: "1620000",
    estimatedPricePerM2: "926",
    landUse: "Tourism commercial",
    servicesAvailable: "Water, electricity, road and beach access",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "sofia-quesada",
    notes: "Confirm coastal concession and permitted use before investor package.",
  }),
  makeRequest({
    id: "request-curridabat-medical-corridor",
    status: "Approved",
    submittedAt: "2026-05-14T18:25:00.000Z",
    ownerName: "Luis Diego Quiros",
    email: "luis.quiros@example.com",
    phone: "+506 7109 4401",
    title: "Granadilla Medical Corridor Lot",
    province: "San Jose",
    canton: "Curridabat",
    district: "Granadilla",
    exactAddress: "Granadilla, east of Pinares medical and retail corridor",
    propertyType: "mixed-use parcel",
    landSizeM2: "1550",
    ownerAskingPrice: "1120000",
    estimatedPricePerM2: "723",
    landUse: "Medical and services",
    servicesAvailable: "Water, electricity, fiber, paved road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "laura-mendez",
    notes: "Strong medical services positioning; verify parking ratio.",
  }),
  makeRequest({
    id: "request-grecia-view-land",
    status: "New",
    submittedAt: "2026-05-13T21:15:00.000Z",
    ownerName: "Patricia Mena",
    email: "patricia.mena@example.com",
    phone: "+506 8533 7140",
    title: "Grecia View Residential Land",
    province: "Alajuela",
    canton: "Grecia",
    district: "Grecia",
    exactAddress: "North Grecia hillside, paved road and valley view",
    propertyType: "residential development land",
    landSizeM2: "5200",
    ownerAskingPrice: "860000",
    estimatedPricePerM2: "165",
    landUse: "Low-density residential",
    servicesAvailable: "Electricity and water nearby, septic required",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    roadAccess: "Paved public road",
    preferredBrokerId: "esteban-mora",
    notes: "Owner wants family development positioning, not agricultural pricing.",
  }),
  makeRequest({
    id: "request-alajuela-coyol-industrial",
    status: "In Review",
    submittedAt: "2026-05-12T14:05:00.000Z",
    ownerName: "Hector Salazar",
    email: "hector.salazar@example.com",
    phone: "+506 8801 3339",
    title: "Coyol Industrial Expansion Site",
    province: "Alajuela",
    canton: "Alajuela",
    district: "Coyol",
    exactAddress: "Coyol industrial corridor, near Route 1 access",
    propertyType: "industrial lot",
    landSizeM2: "9200",
    ownerAskingPrice: "2860000",
    estimatedPricePerM2: "311",
    landUse: "Industrial park support",
    servicesAvailable: "Three-phase electricity, water nearby, truck access",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "oscar-benavides",
    notes: "Confirm industrial zoning and utility capacity documents.",
  }),
  makeRequest({
    id: "request-cartago-tres-rios",
    status: "Needs Info",
    submittedAt: "2026-05-11T17:42:00.000Z",
    ownerName: "Mariana Salas",
    email: "mariana.salas@example.com",
    phone: "+506 7012 8195",
    title: "Tres Rios Mixed-Use Corner",
    province: "Cartago",
    canton: "La Union",
    district: "Tres Rios",
    exactAddress: "Tres Rios, near old road to Cartago commercial services",
    propertyType: "mixed-use parcel",
    landSizeM2: "1620",
    ownerAskingPrice: "700000",
    estimatedPricePerM2: "432",
    landUse: "Residential-commercial mixed use",
    servicesAvailable: "Water, electricity, bus route, paved road",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "karla-picado",
    notes: "Need updated parcel plan before broker package.",
  }),
  makeRequest({
    id: "request-nosara-eco-lodge",
    status: "New",
    submittedAt: "2026-05-10T19:00:00.000Z",
    ownerName: "Elias Murillo",
    email: "elias.murillo@example.com",
    phone: "+506 8720 6602",
    title: "Nosara Eco-Lodge Parcel",
    province: "Guanacaste",
    canton: "Nicoya",
    district: "Nosara",
    exactAddress: "Nosara ridge road, 12 minutes from Guiones",
    propertyType: "hospitality land",
    landSizeM2: "5400",
    ownerAskingPrice: "2620000",
    estimatedPricePerM2: "485",
    landUse: "Eco-hospitality",
    servicesAvailable: "Electricity nearby, private water source reported",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    roadAccess: "Gravel public road",
    preferredBrokerId: "marco-hidalgo",
    notes: "Need dry-season road condition and water proof.",
  }),
  makeRequest({
    id: "request-la-fortuna-lodge",
    status: "Approved",
    submittedAt: "2026-05-09T16:30:00.000Z",
    ownerName: "Daniela Chaves",
    email: "daniela.chaves@example.com",
    phone: "+506 8604 1902",
    title: "La Fortuna Lodge Site",
    province: "Alajuela",
    canton: "San Carlos",
    district: "La Fortuna",
    exactAddress: "La Fortuna, volcano view corridor west of town",
    propertyType: "hospitality land",
    landSizeM2: "6400",
    ownerAskingPrice: "1640000",
    estimatedPricePerM2: "256",
    landUse: "Tourism lodging",
    servicesAvailable: "Water, electricity, road access, tourism services nearby",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    roadAccess: "Paved public road",
    preferredBrokerId: "paola-jimenez",
    notes: "Strong tourism story; verify buildable area and setbacks.",
  }),
  makeRequest({
    id: "request-rohrmoser-embassy",
    status: "In Review",
    submittedAt: "2026-05-08T11:20:00.000Z",
    ownerName: "Jorge Marin",
    email: "jorge.marin@example.com",
    phone: "+506 8828 4146",
    title: "Rohrmoser Embassy Corridor Lot",
    province: "San Jose",
    canton: "San Jose",
    district: "Pavas",
    exactAddress: "Rohrmoser, near embassy corridor and La Sabana access",
    propertyType: "urban lot",
    landSizeM2: "980",
    ownerAskingPrice: "1120000",
    estimatedPricePerM2: "1143",
    landUse: "High-density residential",
    servicesAvailable: "Water, electricity, sewer, fiber",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "gabriel-arias",
    notes: "Owner expects premium pricing due to embassy corridor location.",
  }),
  makeRequest({
    id: "request-san-pedro-student",
    status: "New",
    submittedAt: "2026-05-07T18:05:00.000Z",
    ownerName: "Nora Espinoza",
    email: "nora.espinoza@example.com",
    phone: "+506 7104 2219",
    title: "San Pedro Student Housing Lot",
    province: "San Jose",
    canton: "Montes de Oca",
    district: "San Pedro",
    exactAddress: "San Pedro, walking distance to university corridor",
    propertyType: "residential development land",
    landSizeM2: "840",
    ownerAskingPrice: "548000",
    estimatedPricePerM2: "652",
    landUse: "Student housing",
    servicesAvailable: "Water, electricity, bus and train access nearby",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "natalia-leiva",
    notes: "Parking and height restrictions need review.",
  }),
  makeRequest({
    id: "request-lindora-frontage",
    status: "Approved",
    submittedAt: "2026-05-06T13:55:00.000Z",
    ownerName: "Ignacio Fallas",
    email: "ignacio.fallas@example.com",
    phone: "+506 8980 1442",
    title: "Lindora Commercial Frontage",
    province: "San Jose",
    canton: "Santa Ana",
    district: "Lindora",
    exactAddress: "Lindora main commercial corridor, near office and retail anchors",
    propertyType: "commercial corner",
    landSizeM2: "1980",
    ownerAskingPrice: "1540000",
    estimatedPricePerM2: "778",
    landUse: "Retail and office services",
    servicesAvailable: "Water, electricity, fiber, paved frontage",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "renato-fonseca",
    notes: "High visibility frontage; asking price appears defensible.",
  }),
  makeRequest({
    id: "request-belen-corporate",
    status: "In Review",
    submittedAt: "2026-05-05T15:40:00.000Z",
    ownerName: "Paula Fernandez",
    email: "paula.fernandez@example.com",
    phone: "+506 8899 7024",
    title: "Belen Corporate Corridor Lot",
    province: "Heredia",
    canton: "Belen",
    district: "La Ribera",
    exactAddress: "La Ribera de Belen, near business hotels and office parks",
    propertyType: "mixed-use parcel",
    landSizeM2: "2460",
    ownerAskingPrice: "1440000",
    estimatedPricePerM2: "585",
    landUse: "Corporate corridor services",
    servicesAvailable: "Water, electricity, fiber, airport access",
    waterAvailability: "Available and connected",
    electricityAvailability: "Available and connected",
    roadAccess: "Paved public road",
    preferredBrokerId: "isabel-nunez",
    notes: "Potential service-retail or office support use.",
  }),
  makeRequest({
    id: "request-atenas-ridge",
    status: "Rejected",
    submittedAt: "2026-05-04T20:15:00.000Z",
    ownerName: "Silvia Porras",
    email: "silvia.porras@example.com",
    phone: "+506 8706 3198",
    title: "Atenas Ridge Eco-Lot",
    province: "Alajuela",
    canton: "Atenas",
    district: "Atenas",
    exactAddress: "Atenas ridge road, steep private access",
    propertyType: "mountain eco-lot",
    landSizeM2: "6400",
    ownerAskingPrice: "1280000",
    estimatedPricePerM2: "200",
    landUse: "Eco-residential",
    servicesAvailable: "Electricity nearby, water source unconfirmed",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    roadAccess: "Private road",
    preferredBrokerId: "manuel-cordero",
    notes: "Rejected for MVP listing due to unresolved access and water risk at current price.",
  }),
  makeRequest({
    id: "request-cartago-industrial",
    status: "New",
    submittedAt: "2026-05-03T16:45:00.000Z",
    ownerName: "Mauricio Rivas",
    email: "mauricio.rivas@example.com",
    phone: "+506 8409 6173",
    title: "Cartago Industrial Support Lot",
    province: "Cartago",
    canton: "Cartago",
    district: "Oriental",
    exactAddress: "Cartago industrial edge, access to regional road",
    propertyType: "industrial lot",
    landSizeM2: "5400",
    ownerAskingPrice: "1430000",
    estimatedPricePerM2: "265",
    landUse: "Industrial support",
    servicesAvailable: "Water, electricity, truck access",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    roadAccess: "Paved public road",
    preferredBrokerId: "valeria-castro",
    notes: "Good industrial support candidate if zoning confirms use.",
  }),
  makeRequest({
    id: "request-san-ramon-residential",
    status: "Needs Info",
    submittedAt: "2026-05-02T12:35:00.000Z",
    ownerName: "Andrea Molina",
    email: "andrea.molina@example.com",
    phone: "+506 8741 5600",
    title: "San Ramon Residential Parcel",
    province: "Alajuela",
    canton: "San Ramon",
    district: "San Ramon",
    exactAddress: "San Ramon residential expansion area, near public school",
    propertyType: "residential development land",
    landSizeM2: "4100",
    ownerAskingPrice: "520000",
    estimatedPricePerM2: "127",
    landUse: "Residential expansion",
    servicesAvailable: "Water, electricity, public road",
    waterAvailability: "Available nearby",
    electricityAvailability: "Available nearby",
    roadAccess: "Paved public road",
    preferredBrokerId: "ricardo-sanchez",
    notes: "Need updated municipal land-use letter.",
  }),
  makeRequest({
    id: "request-papagayo-support",
    status: "Approved",
    submittedAt: "2026-05-01T17:18:00.000Z",
    ownerName: "Alejandro Lobo",
    email: "alejandro.lobo@example.com",
    phone: "+506 8891 4502",
    title: "Papagayo Tourism Support Parcel",
    province: "Guanacaste",
    canton: "Liberia",
    district: "Nacascolo",
    exactAddress: "Access road to Papagayo tourism corridor",
    propertyType: "tourism development land",
    landSizeM2: "5200",
    ownerAskingPrice: "1360000",
    estimatedPricePerM2: "262",
    landUse: "Tourism support services",
    servicesAvailable: "Electricity nearby, road access, water to confirm",
    waterAvailability: "Needs validation",
    electricityAvailability: "Available nearby",
    roadAccess: "Paved public road",
    preferredBrokerId: "andres-solis",
    notes: "Solid corridor story; water confirmation required before closing diligence.",
  }),
];
